import type { Producto } from '../types';

export const CATALOGO_LIDER_BASE: Producto[] = [
  // ==========================================
  // CARNES Y AVES
  // ==========================================
  {
    id: 'lid-car-01',
    sku: '684920',
    nombre: 'Pechuga de Pollo Deshuesada Fileteada Bandeja',
    marca: 'Super Pollo',
    precio: 4990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/684920a.jpg]&sink',
    categoriaPasillo: 'carnes_aves',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 95,
    sellosNegros: 0,
    cantidadPresentacion: '700 g aprox',
    precioPorUnidadMedida: '$7.129 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'pechuga pollo deshuesada',
    macros100g: {
      calorias: 110,
      proteinas: 23,
      carbohidratos: 0,
      grasas: 2,
      fibra: 0,
    },
  },
  {
    id: 'lid-car-02',
    sku: '445210',
    nombre: 'Posta Negra Vacuno Molida Tártaro 4% Grasa',
    marca: 'Líder Selección',
    precio: 6490,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/445210a.jpg]&sink',
    categoriaPasillo: 'carnes_aves',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 92,
    sellosNegros: 0,
    cantidadPresentacion: '500 g',
    precioPorUnidadMedida: '$12.980 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'posta negra',
    macros100g: {
      calorias: 125,
      proteinas: 22,
      carbohidratos: 0,
      grasas: 4,
      fibra: 0,
    },
  },
  {
    id: 'lid-car-03',
    sku: '883012',
    nombre: 'Pechuga de Pavo Cocida Acaramelada Laminada',
    marca: 'Sopraval',
    precio: 2390,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/883012a.jpg]&sink',
    categoriaPasillo: 'carnes_aves',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 88,
    sellosNegros: 0,
    cantidadPresentacion: '200 g',
    precioPorUnidadMedida: '$11.950 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'jamon pavo',
    macros100g: {
      calorias: 105,
      proteinas: 20,
      carbohidratos: 2,
      grasas: 1.5,
      fibra: 0,
    },
  },
  {
    id: 'lid-car-04',
    sku: '556102',
    nombre: 'Lomo Centro de Cerdo Magro Fileteado',
    marca: 'Super Cerdo',
    precio: 4790,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/556102a.jpg]&sink',
    categoriaPasillo: 'carnes_aves',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 89,
    sellosNegros: 0,
    cantidadPresentacion: '700 g',
    precioPorUnidadMedida: '$6.840 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'lomo centro cerdo',
    macros100g: {
      calorias: 135,
      proteinas: 22,
      carbohidratos: 0,
      grasas: 5,
      fibra: 0,
    },
  },

  // ==========================================
  // PESCADOS Y MARISCOS
  // ==========================================
  {
    id: 'lid-pes-01',
    sku: '723145',
    nombre: 'Filete de Salmón del Sur Congelado al Vacío',
    marca: 'Líder',
    precio: 7990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/723145a.jpg]&sink',
    categoriaPasillo: 'pescados_mariscos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 94,
    sellosNegros: 0,
    cantidadPresentacion: '500 g',
    precioPorUnidadMedida: '$15.980 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'salmon porciones',
    macros100g: {
      calorias: 180,
      proteinas: 20,
      carbohidratos: 0,
      grasas: 11,
      fibra: 0,
    },
  },
  {
    id: 'lid-pes-02',
    sku: '331908',
    nombre: 'Filete de Merluza Austral Congelada',
    marca: 'El Golfo',
    precio: 4990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/331908a.jpg]&sink',
    categoriaPasillo: 'pescados_mariscos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 93,
    sellosNegros: 0,
    cantidadPresentacion: '600 g',
    precioPorUnidadMedida: '$8.316 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'merluza filete',
    macros100g: {
      calorias: 85,
      proteinas: 18,
      carbohidratos: 0,
      grasas: 1,
      fibra: 0,
    },
  },

  // ==========================================
  // LÁCTEOS Y HUEVOS
  // ==========================================
  {
    id: 'lid-lac-01',
    sku: '119280',
    nombre: 'Huevos Blancos Grandes Bandeja 30 unidades',
    marca: 'Líder',
    precio: 6990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/119280a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 92,
    sellosNegros: 0,
    cantidadPresentacion: 'Bandeja 30 un',
    precioPorUnidadMedida: '$233 / unidad',
    disponibleEnCasona: true,
    terminoBusqueda: 'huevos grandes',
    macros100g: {
      calorias: 145,
      proteinas: 13,
      carbohidratos: 1,
      grasas: 10,
      fibra: 0,
    },
  },
  {
    id: 'lid-lac-02',
    sku: '990142',
    nombre: 'Claras de Huevo Pasteurizadas en Botella',
    marca: 'Gallina Blanca',
    precio: 3490,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/990142a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 98,
    sellosNegros: 0,
    cantidadPresentacion: '1 Litro (aprox 30 claras)',
    precioPorUnidadMedida: '$3.490 / L',
    disponibleEnCasona: true,
    terminoBusqueda: 'claras de huevo',
    macros100g: {
      calorias: 50,
      proteinas: 11,
      carbohidratos: 1,
      grasas: 0.2,
      fibra: 0,
    },
  },
  {
    id: 'lid-lac-03',
    sku: '881239',
    nombre: 'Leche Descremada Protein+ 15g Proteína',
    marca: 'Colun',
    precio: 1490,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/881239a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 96,
    sellosNegros: 0,
    cantidadPresentacion: '1 Litro',
    precioPorUnidadMedida: '$1.490 / L',
    disponibleEnCasona: true,
    terminoBusqueda: 'leche protein',
    macros100g: {
      calorias: 48,
      proteinas: 6,
      carbohidratos: 4.8,
      grasas: 0.3,
      fibra: 0,
    },
  },
  {
    id: 'lid-lac-04',
    sku: '665123',
    nombre: 'Yogurt Griego Protein Natural sin Azúcar 15g',
    marca: 'Colun',
    precio: 990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/665123a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 97,
    sellosNegros: 0,
    cantidadPresentacion: '150 g',
    precioPorUnidadMedida: '$6.600 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'yogurt protein',
    macros100g: {
      calorias: 68,
      proteinas: 10,
      carbohidratos: 4,
      grasas: 0.1,
      fibra: 0,
    },
  },
  {
    id: 'lid-lac-05',
    sku: '441209',
    nombre: 'Quesillo Fresco Tradicional Sureño de Osorno',
    marca: 'Colun',
    precio: 2190,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/441209a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 91,
    sellosNegros: 0,
    cantidadPresentacion: '320 g',
    precioPorUnidadMedida: '$6.840 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'quesillo',
    macros100g: {
      calorias: 98,
      proteinas: 12,
      carbohidratos: 3.5,
      grasas: 3.8,
      fibra: 0,
    },
  },
  {
    id: 'lid-lac-06',
    sku: '552310',
    nombre: 'Queso Ricotta Magro',
    marca: 'Colun',
    precio: 1990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/552310a.jpg]&sink',
    categoriaPasillo: 'lacteos_huevos',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 89,
    sellosNegros: 0,
    cantidadPresentacion: '250 g',
    precioPorUnidadMedida: '$7.960 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'ricotta',
    macros100g: {
      calorias: 110,
      proteinas: 11,
      carbohidratos: 4,
      grasas: 5,
      fibra: 0,
    },
  },

  // ==========================================
  // PANADERÍA Y CEREALES
  // ==========================================
  {
    id: 'lid-pan-01',
    sku: '100412',
    nombre: 'Avena Instantánea Tradicional Bolsa',
    marca: 'Líder',
    precio: 1790,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/100412a.jpg]&sink',
    categoriaPasillo: 'panaderia_cereales',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 93,
    sellosNegros: 0,
    cantidadPresentacion: '800 g',
    precioPorUnidadMedida: '$2.238 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'avena instantanea',
    macros100g: {
      calorias: 375,
      proteinas: 13,
      carbohidratos: 66,
      grasas: 6.5,
      fibra: 10,
    },
  },
  {
    id: 'lid-pan-02',
    sku: '219001',
    nombre: 'Marraqueta Tradicional Horneada en Tienda',
    marca: 'Panadería Líder Casona',
    precio: 1990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/219001a.jpg]&sink',
    categoriaPasillo: 'panaderia_cereales',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 82,
    sellosNegros: 0,
    cantidadPresentacion: '1 kg granel',
    precioPorUnidadMedida: '$1.990 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'marraqueta',
    macros100g: {
      calorias: 260,
      proteinas: 9,
      carbohidratos: 52,
      grasas: 1,
      fibra: 3,
    },
  },
  {
    id: 'lid-pan-03',
    sku: '772109',
    nombre: 'Pan de Molde 100% Integral Grano Entero',
    marca: 'Fuchs',
    precio: 2690,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/772109a.jpg]&sink',
    categoriaPasillo: 'panaderia_cereales',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 91,
    sellosNegros: 0,
    cantidadPresentacion: '550 g',
    precioPorUnidadMedida: '$4.890 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'pan molde integral',
    macros100g: {
      calorias: 240,
      proteinas: 11,
      carbohidratos: 41,
      grasas: 2.5,
      fibra: 8.5,
    },
  },

  // ==========================================
  // FRUTAS Y VERDURAS
  // ==========================================
  {
    id: 'lid-fru-01',
    sku: '300129',
    nombre: 'Palta Hass Primera Selección Granel',
    marca: 'Líder Campo',
    precio: 4990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/300129a.jpg]&sink',
    categoriaPasillo: 'frutas_verduras',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 90,
    sellosNegros: 0,
    cantidadPresentacion: '1 kg granel',
    precioPorUnidadMedida: '$4.990 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'palta hass',
    macros100g: {
      calorias: 160,
      proteinas: 2,
      carbohidratos: 8.5,
      grasas: 14.5,
      fibra: 6.7,
    },
  },
  {
    id: 'lid-fru-02',
    sku: '120938',
    nombre: 'Zapallo Camote Trozo Fresco Granel',
    marca: 'Líder Campo',
    precio: 1490,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/120938a.jpg]&sink',
    categoriaPasillo: 'frutas_verduras',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 92,
    sellosNegros: 0,
    cantidadPresentacion: '1 kg granel',
    precioPorUnidadMedida: '$1.490 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'zapallo camote',
    macros100g: {
      calorias: 30,
      proteinas: 1.2,
      carbohidratos: 7,
      grasas: 0.1,
      fibra: 2.5,
    },
  },
  {
    id: 'lid-fru-03',
    sku: '449102',
    nombre: 'Papas Granel Malla Lavadas Selección',
    marca: 'Líder Campo',
    precio: 2990,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/449102a.jpg]&sink',
    categoriaPasillo: 'frutas_verduras',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 86,
    sellosNegros: 0,
    cantidadPresentacion: '2 kg malla',
    precioPorUnidadMedida: '$1.495 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'papas granel',
    macros100g: {
      calorias: 77,
      proteinas: 2,
      carbohidratos: 17,
      grasas: 0.1,
      fibra: 2.2,
    },
  },
  {
    id: 'lid-fru-04',
    sku: '228190',
    nombre: 'Plátano Cavendish Granel',
    marca: 'Líder',
    precio: 1590,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/228190a.jpg]&sink',
    categoriaPasillo: 'frutas_verduras',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 88,
    sellosNegros: 0,
    cantidadPresentacion: '1 kg',
    precioPorUnidadMedida: '$1.590 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'platano',
    macros100g: {
      calorias: 89,
      proteinas: 1.1,
      carbohidratos: 23,
      grasas: 0.3,
      fibra: 2.6,
    },
  },

  // ==========================================
  // BEBIDAS (GUSTOS DEL MES)
  // ==========================================
  {
    id: 'lid-beb-01',
    sku: '900213',
    nombre: 'Bebida Coca-Cola Sin Azúcar Pack 6 Latas',
    marca: 'Coca-Cola',
    precio: 4290,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/900213a.jpg]&sink',
    categoriaPasillo: 'bebidas',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 75,
    sellosNegros: 0,
    cantidadPresentacion: 'Pack 6 x 350 ml (2.1 L)',
    precioPorUnidadMedida: '$2.043 / L',
    disponibleEnCasona: true,
    terminoBusqueda: 'coca cola sin azucar',
    macros100g: {
      calorias: 0,
      proteinas: 0,
      carbohidratos: 0,
      grasas: 0,
      fibra: 0,
    },
  },
  {
    id: 'lid-beb-02',
    sku: '900214',
    nombre: 'Bebida Coca-Cola Sin Azúcar Botella Familiar Retornable',
    marca: 'Coca-Cola',
    precio: 1890,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/900214a.jpg]&sink',
    categoriaPasillo: 'bebidas',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 80,
    sellosNegros: 0,
    cantidadPresentacion: '2.5 Litros',
    precioPorUnidadMedida: '$756 / L (Mejor precio por litro)',
    disponibleEnCasona: true,
    terminoBusqueda: 'coca cola zero familiar',
    macros100g: {
      calorias: 0,
      proteinas: 0,
      carbohidratos: 0,
      grasas: 0,
      fibra: 0,
    },
  },

  // ==========================================
  // DESPENSA Y ABARROTES
  // ==========================================
  {
    id: 'lid-des-01',
    sku: '601290',
    nombre: 'Lomitos de Atún al Agua Abre Fácil',
    marca: 'San José',
    precio: 1390,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/601290a.jpg]&sink',
    categoriaPasillo: 'despensa_abarrotes',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 96,
    sellosNegros: 0,
    cantidadPresentacion: '160 g',
    precioPorUnidadMedida: '$8.688 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'atun al agua',
    macros100g: {
      calorias: 110,
      proteinas: 24,
      carbohidratos: 0,
      grasas: 1.5,
      fibra: 0,
    },
  },
  {
    id: 'lid-des-02',
    sku: '802194',
    nombre: 'Aceite de Oliva Extra Virgen Botella',
    marca: 'Líder Selección',
    precio: 7490,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/802194a.jpg]&sink',
    categoriaPasillo: 'despensa_abarrotes',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 90,
    sellosNegros: 0,
    cantidadPresentacion: '500 ml',
    precioPorUnidadMedida: '$14.980 / L',
    disponibleEnCasona: true,
    terminoBusqueda: 'aceite de oliva',
    macros100g: {
      calorias: 884,
      proteinas: 0,
      carbohidratos: 0,
      grasas: 100,
      fibra: 0,
    },
  },
  {
    id: 'lid-des-03',
    sku: '109283',
    nombre: 'Arroz Grado 1 Grano Largo Ancho',
    marca: 'Tucapel',
    precio: 1690,
    precioReferencial: false,
    urlFoto: 'https://images.lider.cl/wmtcl?source=url[file:/productos/109283a.jpg]&sink',
    categoriaPasillo: 'despensa_abarrotes',
    fechaActualizacion: new Date().toISOString(),
    vendedorTipo: 'directo_lider',
    puntajeNutricional: 84,
    sellosNegros: 0,
    cantidadPresentacion: '1 kg',
    precioPorUnidadMedida: '$1.690 / kg',
    disponibleEnCasona: true,
    terminoBusqueda: 'arroz grado 1',
    macros100g: {
      calorias: 350,
      proteinas: 7,
      carbohidratos: 79,
      grasas: 0.6,
      fibra: 1.2,
    },
  },
];
