import type { Receta } from '../types';

export const SEMILLAS_RECETAS: Receta[] = [
  // ==========================================
  // DESAYUNOS (8) — RÁPIDOS (2 A 6 MINUTOS)
  // ==========================================
  {
    id: 'des-01',
    nombre: 'Huevos Revueltos Express con Marraqueta y Palta',
    descripcion: 'Desayuno chileno clásico de 6 minutos: 2 huevos enteros en sartén rápida, marraqueta crocante al tostador y palta fresca molida.',
    categoria: 'desayuno',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 460,
      proteinas: 22,
      carbohidratos: 46,
      grasas: 20,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Palta Hass', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner la marraqueta en el tostador a fuego medio.',
      'Cascar 2 huevos enteros directo en la sartén caliente con unas gotas de aceite.',
      'Revolver con espátula a fuego medio solo 2-3 minutos hasta que cuajen tiernos.',
      'Moler la palta con tenedor en el plato con una pizca de sal, untar el pan y servir todo junto.',
    ],
  },
  {
    id: 'des-02',
    nombre: 'Bowl Crujiente de Granola con Yogurt Protein y Plátano',
    descripcion: 'Desayuno o pre-entreno listo en 2 minutos en un tazón: yogurt griego/protein cremoso con granola crocante Quaker miel y almendras y plátano en rodajas. Cero cocción.',
    categoria: 'desayuno',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 380,
      proteinas: 18,
      carbohidratos: 68,
      grasas: 5,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Yogurt tipo griego natural protein', cantidad: 155, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Granola con miel y almendras', cantidad: 25, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'granola quaker miel almendra' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'canela molida' },
    ],
    instrucciones: [
      'En un tazón, verter el pote de yogurt tipo griego protein.',
      'Añadir la granola crujiente por encima.',
      'Cortar el plátano en rodajas con cuchillo, toque de canela opcional y disfrutar.',
    ],
  },
  {
    id: 'des-03',
    nombre: 'Tostadas Rápidas con Quesillo Sureño y Jamón Pierna',
    descripcion: 'Desayuno fresco sin sartenes listo en 3 minutos: pan tostado crujiente con quesillo fresco de Osorno y jamón pierna magro artesanal.',
    categoria: 'desayuno',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 290,
      proteinas: 18,
      carbohidratos: 36,
      grasas: 6,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Jamón Pierna tradicional envasado', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pierna tradicional' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la rebanada de pan integral en el tostador.',
      'Cortar 1 lámina de quesillo y rodajas de tomate.',
      'Montar el jamón pierna, el quesillo y el tomate sobre la tostada con una pizca de orégano.',
    ],
  },
  {
    id: 'des-04',
    nombre: 'Omelette Express de 2 Huevos con Quesillo y Orégano',
    descripcion: 'Una sola sartén, 5 minutos de cocción total. Proteína pura compacta y digestiva.',
    categoria: 'desayuno',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 300,
      proteinas: 20,
      carbohidratos: 4,
      grasas: 21,
      fibra: 0.5,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano y sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Batir rápidamente los 2 huevos en un tazón con tenedor y una pizca de sal.',
      'Calentar la sartén con gotas de aceite y verter el huevo batido.',
      'Añadir trozos de quesillo sobre una mitad y espolvorear orégano.',
      'Doblar el omelette por la mitad con espátula y servir caliente.',
    ],
  },
  {
    id: 'des-05',
    nombre: 'Parfait Crujiente de Granola con Leche Proteica y Arándanos',
    descripcion: 'Desayuno fitness fresco listo en 1 minuto: granola crocante con almendras, leche proteica y arándanos frescos.',
    categoria: 'desayuno',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 280,
      proteinas: 13,
      carbohidratos: 48,
      grasas: 5,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Granola con miel y almendras', cantidad: 25, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'granola' },
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 150, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein colun' },
      { nombre: 'Arándanos frescos o congelados', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'arandanos' },
    ],
    instrucciones: [
      'En un tazón, verter la granola crujiente.',
      'Agregar la leche proteica fría y coronar con los arándanos frescos.',
      'Comer con cuchara al instante.',
    ],
  },
  {
    id: 'des-06',
    nombre: 'Tostada Crujiente con Palta y Jamón Pierna al Tostador',
    descripcion: 'Rápido, crocante y saciante: pan integral tostado con palta hass y jamón pierna artesanal seleccionado.',
    categoria: 'desayuno',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 260,
      proteinas: 13,
      carbohidratos: 26,
      grasas: 11,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Palta Hass', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Jamón Pierna tradicional envasado', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pierna tradicional' },
      { nombre: 'Sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la rebanada de pan integral.',
      'Moler la palta con tenedor en un plato con una pizca de sal.',
      'Untar la palta sobre el pan tostado y poner encima las láminas de jamón pierna.',
    ],
  },
  {
    id: 'des-07',
    nombre: 'Sándwich de Huevo Duro y Pechuga de Pavo en Marraqueta',
    descripcion: 'Rápido, contundente y tradicional. Con 1 huevo cocido, se arma en solo 2 minutos.',
    categoria: 'desayuno',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 390,
      proteinas: 21,
      carbohidratos: 48,
      grasas: 11,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Pechuga / Jamón de pavo', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pavo' },
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
    ],
    instrucciones: [
      'Tostar la marraqueta en tostador.',
      'Picar el huevo duro en rodajas.',
      'Rellenar el pan tostado con las láminas de pavo y el huevo en rodajas con pizca de sal.',
    ],
  },
  {
    id: 'des-08',
    nombre: 'Tazón de Granola Crocante con Leche Proteica Tibia y Toque de Cacao',
    descripcion: 'Listo en 2 minutos: calientas la leche proteica con un toque de cacao amargo al microondas, agregas la granola y disfrutas crujiente.',
    categoria: 'desayuno',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 330,
      proteinas: 17,
      carbohidratos: 52,
      grasas: 6,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Granola con miel y almendras', cantidad: 25, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'granola' },
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 200, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein colun' },
      { nombre: 'Cacao amargo en polvo puro', cantidad: 5, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'cacao amargo' },
    ],
    instrucciones: [
      'Calentar la leche proteica 45 segundos en el microondas dentro de un tazón.',
      'Disolver la cucharadita de cacao amargo con cuchara.',
      'Verter la granola crocante por encima y comer de inmediato.',
    ],
  },

  // ==========================================
  // ALMUERZOS (12) — PRE-ENTRENO Y FUERZA (10 A 15 MINUTOS)
  // ==========================================
  {
    id: 'alm-01',
    nombre: 'Potes de Arroz Blanco con Pollo Doradito en Cubos y Mix de Ensalada Toscana con Mayo Kraft',
    descripcion: 'Almuerzo estándar de batch cooking: cubos de pechuga dorados con arroz blanco, porción fresca de mix toscana y mayonesa Kraft. Ideal para preparar 5 potes.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 29,
      carbohidratos: 74,
      grasas: 18,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 85, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Cortar la pechuga en cubos y dorar en sartén caliente con gotas de aceite por 5 minutos.',
      'Servir con porción de arroz blanco caliente (80g en seco cocido).',
      'Acompañar con la porción fresca de Ensalada Mix Toscana y 1 cucharada (15g) de Mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Cocina en una sola olla 400g de arroz y dora 425g de pollo en sartén. Reparte equitativamente en 5 potes herméticos al refrigerador. Al momento de comer, calientas 2 min y agregas la porción fresca de ensalada mix y mayo.',
    ],
  },
  {
    id: 'alm-02',
    nombre: 'Potes de Fideos Spaghetti con Carne Molida (Posta Negra) y Salsa de Tomate',
    descripcion: 'El clásico infalible de fuerza: fideos al dente con carne molida magra de posta negra desmenuzada y salsa de tomate natural. Gramos exactos para 5 potes.',
    categoria: 'almuerzo',
    tiempoMinutos: 11,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 28,
      carbohidratos: 78,
      grasas: 10,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Posta negra de vacuno', cantidad: 90, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Fideos spaghetti o tallarines', cantidad: 80, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'spaghetti' },
      { nombre: 'Tomate chileno', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Hervir los fideos en olla con agua caliente y sal por 8 minutos al dente.',
      'En una sartén con gotas de aceite, dorar la carne molida de posta negra desmenuzándola con espátula.',
      'Agregar el tomate picado en cubitos con orégano a la carne para formar una salsa jugosa natural.',
      'Mezclar los fideos con la carne y servir caliente.',
      '💡 Tip Batch Cooking (5 potes): Hierve el paquete de fideos (400g) y saltea 450g de posta molida con 5 tomates. Distribuye en 5 potes herméticos para la semana con los mismos gramos exactos.',
    ],
  },
  {
    id: 'alm-03',
    nombre: 'Potes de Papas al Microondas con Hamburguesas Caseras de Vacuno y Ensalada Toscana',
    descripcion: 'Hamburguesas magras caseras doradas en sartén con papas al vapor y ensalada mix toscana fresca con mayonesa Kraft.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 530,
      proteinas: 27,
      carbohidratos: 54,
      grasas: 21,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Posta negra de vacuno', cantidad: 90, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Papas granel', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Pinchar la papa con un tenedor y cocinarla en microondas por 5 minutos a potencia máxima.',
      'Aplanar la posta molida en forma de hamburguesa y dorar en sartén 3 minutos por lado.',
      'Abrir la papa al vapor y servir con la hamburguesa, la ensalada toscana fresca y 1 cucharada de Mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Puedes cocer 5 papas al microondas o vapor y dorar 5 hamburguesas de 90g. Guarda en potes individuales en el refrigerador.',
    ],
  },
  {
    id: 'alm-04',
    nombre: 'Potes de Arroz Chaufa Universitario Fit de Pollo y Huevo',
    descripcion: 'Una sola sartén, 8 minutos: salteas trozos de pollo, arroz cocido y 1 huevo revuelto todo junto. Excelente para guardar en potes.',
    categoria: 'almuerzo',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 530,
      proteinas: 30,
      carbohidratos: 75,
      grasas: 11,
      fibra: 2,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Cortar la pechuga en cubos y dorarla en la sartén a fuego alto durante 3 minutos.',
      'Apartar a un lado de la sartén, quebrar el huevo y revolver rápidamente 30 segundos.',
      'Integrar el arroz cocido, saltear todo junto a fuego vivo por 2 minutos y servir.',
      '💡 Tip Batch Cooking (5 potes): Prepara una tanda grande en wok o sartén grande con 400g de arroz, 400g de pollo y 5 huevos, y porciona en 5 potes.',
    ],
  },
  {
    id: 'alm-05',
    nombre: 'Potes de Fideos Spaghetti con Pollo Fileteado y Ensalada Mix Toscana',
    descripcion: 'Fideos al dente con filete de pechuga dorada al orégano y mix de ensalada toscana crujiente con toque de mayonesa Kraft.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 550,
      proteinas: 29,
      carbohidratos: 76,
      grasas: 16,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 85, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Fideos spaghetti o tallarines', cantidad: 80, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'spaghetti' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Hervir los fideos 8 minutos y escurrir.',
      'Dorar la pechuga de pollo en tiras o filetes delgados en sartén caliente con gotas de aceite y orégano.',
      'Servir los fideos con el pollo dorado, acompañando con ensalada mix toscana y mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Cocina 400g de fideos y 425g de pollo. Distribuye en 5 potes herméticos y deja la ensalada para servir fresca.',
    ],
  },
  {
    id: 'alm-06',
    nombre: 'Potes de Arroz Blanco con Lomitos de Atún y Mayonesa Kraft Express',
    descripcion: 'Almuerzo frío o tibio de 3 minutos: arroz blanco con lomitos de atún al agua desmenuzados y mayonesa Kraft. Perfecto para llevar en pote.',
    categoria: 'almuerzo',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 31,
      carbohidratos: 74,
      grasas: 13,
      fibra: 2,
    },
    ingredientes: [
      { nombre: 'Lomitos de atún al agua', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Limón fresco', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Abrir y escurrir la lata de atún al agua.',
      'Mezclar el atún con el arroz cocido, tomate picado en dados y una cucharada de Mayonesa Kraft con unas gotas de limón.',
      '💡 Tip Batch Cooking (5 potes): Cocina una olla de 400g de arroz para la semana y porciona en 5 potes; cada día abres una lata de atún con tu mayonesa Kraft.',
    ],
  },
  {
    id: 'alm-07',
    nombre: 'Potes de Arroz con Posta Negra Salteada en Tiras y Ensalada Toscana',
    descripcion: 'Tiras de posta negra selladas a la plancha con arroz blanco y ensalada toscana fresca con mayonesa Kraft.',
    categoria: 'almuerzo',
    tiempoMinutos: 9,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 29,
      carbohidratos: 74,
      grasas: 19,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Posta negra de vacuno', cantidad: 90, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Cortar la posta en tiras y dorar a fuego alto 3 minutos en sartén con gotas de aceite.',
      'Servir con arroz blanco caliente y la ensalada toscana fresca aliñada con mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Saltea 450g de posta en tiras y cocina 400g de arroz. Reparte en 5 potes para la semana.',
    ],
  },
  {
    id: 'alm-08',
    nombre: 'Potes de Pechuga de Pollo al Limón con Arroz y Ensalada Toscana',
    descripcion: 'Pechuga dorada con un toque de limón fresco, arroz blanco y crujiente mix de ensalada toscana con mayonesa Kraft.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 550,
      proteinas: 28,
      carbohidratos: 74,
      grasas: 17,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Limón fresco', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Dorar el filete de pollo en sartén caliente con gotas de aceite.',
      'Exprimir medio limón directamente sobre el pollo en los últimos segundos.',
      'Servir con arroz blanco caliente y ensalada mix toscana con mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Porciona en 5 potes el arroz con el pollo al limón ya doradito.',
    ],
  },
  {
    id: 'alm-09',
    nombre: 'Salteado Express de Carne Molida Magra con Arroz y Ensalada Toscana',
    descripcion: 'Sabor casero y rápido: carne molida magra sellada a fuego alto, acompañada de arroz blanco y ensalada mix toscana fresca.',
    categoria: 'almuerzo',
    tiempoMinutos: 9,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 550,
      proteinas: 26,
      carbohidratos: 74,
      grasas: 18,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Posta negra de vacuno', cantidad: 90, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 35, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Dorar la carne molida con pizca de sal en la sartén durante 3 minutos.',
      'Servir sobre el arroz caliente junto a la ensalada toscana fresca y mayonesa Kraft.',
      '💡 Tip Batch Cooking (5 potes): Saltea 450g de carne molida y reparte en 5 potes con arroz.',
    ],
  },
  {
    id: 'alm-10',
    nombre: 'Merluza Austral en Sartén con Papas al Microondas y Limón',
    descripcion: 'Pescado blanco sureño suave y digestivo: filete de merluza dorado 4 minutos con papa al vapor y abundante limón.',
    categoria: 'almuerzo',
    tiempoMinutos: 9,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 440,
      proteinas: 26,
      carbohidratos: 52,
      grasas: 9,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Filete de merluza austral', cantidad: 100, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'merluza filetes' },
      { nombre: 'Papas granel', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Limón fresco', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Cocinar la papa al microondas por 5 minutos.',
      'Secar el filete de merluza con toalla de papel y dorar en sartén antiadherente con gotas de aceite, 2 minutos por lado.',
      'Rociar con jugo de limón fresco y servir con la papa al vapor.',
    ],
  },
  {
    id: 'alm-11',
    nombre: 'Fajitas / Wraps Rápidos de Pollo con Palta, Tomate y Mayonesa Kraft',
    descripcion: 'Comida práctica: tiras de pollo a la plancha envueltas en tortilla de trigo con palta molida, dados de tomate y toque de mayonesa Kraft.',
    categoria: 'almuerzo',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 27,
      carbohidratos: 48,
      grasas: 20,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Tortillas de trigo integrales (rapiditas)', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'tortillas rapiditas' },
      { nombre: 'Palta Hass', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Saltear las tiras de pollo en sartén durante 4 minutos.',
      'Calentar la tortilla 20 segundos en sartén o microondas.',
      'Rellenar la tortilla con pollo, palta molida, dados de tomate y 1 cucharada de Mayonesa Kraft.',
    ],
  },
  {
    id: 'alm-12',
    nombre: 'Potes de Fideos con Pechuga de Pavo Salteada y Champiñones',
    descripcion: 'Salteado exprés de fideos con pechuga de pavo en tiras y champiñones laminados. Excelente para meal prep en pote.',
    categoria: 'almuerzo',
    tiempoMinutos: 9,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 25,
      carbohidratos: 76,
      grasas: 7,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga / Jamón de pavo', cantidad: 50, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pavo' },
      { nombre: 'Fideos spaghetti o tallarines', cantidad: 80, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'spaghetti' },
      { nombre: 'Champiñones laminados', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champiñones' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Hervir los fideos 8 minutos y escurrir.',
      'En la sartén con gotas de aceite, saltear los champiñones y las tiras de pavo por 2 minutos.',
      'Añadir los fideos cocidos, saltear todo junto 1 minuto y servir caliente.',
      '💡 Tip Batch Cooking (5 potes): Porciona en 5 potes con los fideos cocidos y el salteado de pavo y champiñones.',
    ],
  },

  // ==========================================
  // COLACIONES (6) — POST-ENTRENO Y SNACKS (1 A 3 MINUTOS)
  // ==========================================
  {
    id: 'col-01',
    nombre: 'Yogurt Griego Protein con Plátano en Rodajas',
    descripcion: 'Colación fresca lista en 1 minuto: pote de yogurt natural con proteína y un plátano rebanado por encima.',
    categoria: 'colacion',
    tiempoMinutos: 1,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 240,
      proteinas: 15,
      carbohidratos: 38,
      grasas: 2,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Yogurt tipo griego natural protein', cantidad: 155, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
    ],
    instrucciones: [
      'Abrir el pote de yogurt y verter en un tazón.',
      'Rebanar el plátano por encima y comer con cuchara.',
    ],
  },
  {
    id: 'col-02',
    nombre: 'Lata de Atún al Agua con Limón y Galletas Integrales',
    descripcion: 'Puro músculo al paso: destapar la lata de atún, rociar limón y acompañar con galletas integrales crujientes.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 260,
      proteinas: 26,
      carbohidratos: 25,
      grasas: 3,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Lomitos de atún al agua', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Galletas de agua integrales', cantidad: 6, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'galletas de agua' },
      { nombre: 'Limón fresco', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Abrir y escurrir el agua de la lata de atún.',
      'Servir en un plato hondo con abundante jugo de limón y pizca de sal.',
      'Comer montando sobre las galletas de agua.',
    ],
  },
  {
    id: 'col-03',
    nombre: 'Rollitos de Pechuga de Pavo con Quesillo Fresco',
    descripcion: 'Snack frío de 2 minutos: láminas de jamón de pavo envolviendo bastones de quesillo fresco con orégano.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 140,
      proteinas: 15,
      carbohidratos: 3,
      grasas: 5,
      fibra: 0.5,
    },
    ingredientes: [
      { nombre: 'Pechuga / Jamón de pavo', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pavo' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Cortar el quesillo en bastones alargados.',
      'Enrollar cada bastón dentro de una lámina de jamón de pavo.',
      'Espolvorear con orégano y comer directo con la mano.',
    ],
  },
  {
    id: 'col-04',
    nombre: 'Shaker Post-Entreno de Proteína en Polvo (Whey) con Plátano',
    descripcion: 'Recuperación muscular inmediata post-gym: 1 scoop de tu proteína Whey en agua fría con un plátano maduro.',
    categoria: 'colacion',
    tiempoMinutos: 1,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 240,
      proteinas: 25,
      carbohidratos: 30,
      grasas: 2,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Suplemento de proteína Whey chocolate tarro', cantidad: 30, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'whey protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
    ],
    instrucciones: [
      'Colocar 1 scoop (30g) de proteína en tu shaker con 250ml de agua.',
      'Agitar enérgicamente durante 15 segundos hasta disolver.',
      'Beber de inmediato y acompañar con el plátano.',
    ],
  },
  {
    id: 'col-05',
    nombre: 'Snack Crunch de Granola con Yogurt Griego Protein',
    descripcion: 'Crocante, proteico y dulce: 1 pote de yogurt protein mezclado con un toque de granola crujiente.',
    categoria: 'colacion',
    tiempoMinutos: 1,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 200,
      proteinas: 15,
      carbohidratos: 24,
      grasas: 4,
      fibra: 2,
    },
    ingredientes: [
      { nombre: 'Granola con miel y almendras', cantidad: 15, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'granola' },
      { nombre: 'Yogurt tipo griego natural protein', cantidad: 155, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
    ],
    instrucciones: [
      'Abrir el pote de yogurt protein.',
      'Verter encima la granola crujiente y disfrutar con cuchara.',
    ],
  },
  {
    id: 'col-06',
    nombre: 'Manzana Verde en Gajos con Toque de Canela y Té Caliente',
    descripcion: 'Snack crocante, fresco y liviano: manzana verde cortada en gajos con toque de canela y una taza de té ceilán.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 110,
      proteinas: 1,
      carbohidratos: 26,
      grasas: 0.5,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Manzana verde granny smith', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'manzana verde' },
      { nombre: 'Bolsita de té negro ceilán', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'bebidas', opcional: false, terminoBusquedaLider: 'te negro' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Lavar y cortar la manzana verde en gajos.',
      'Espolvorear con canela en polvo.',
      'Acompañar con una taza de té caliente.',
    ],
  },

  // ==========================================
  // ONCES (8) — TRADICIONALES CHILENAS (3 A 5 MINUTOS)
  // ==========================================
  {
    id: 'onc-01',
    nombre: 'Once Chilena Tradicional: Marraqueta con Palta y 1 Huevo Revuelto',
    descripcion: 'La once chilena por excelencia: marraqueta tostada con palta molida y 1 huevo tierno al sartén con té caliente.',
    categoria: 'once',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 420,
      proteinas: 16,
      carbohidratos: 48,
      grasas: 16,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Palta Hass', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Bolsita de té negro ceilán', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'bebidas', opcional: false, terminoBusquedaLider: 'te negro' },
    ],
    instrucciones: [
      'Poner el agua a hervir para el té y tostar la marraqueta.',
      'Revolver 1 huevo en la sartén caliente con gotas de aceite.',
      'Moler la palta, untar la marraqueta, montar el huevo y acompañar con la taza de té.',
    ],
  },
  {
    id: 'onc-02',
    nombre: 'Barros Luco Express de Jamón Pierna Dorado con Queso Caliente en Marraqueta',
    descripcion: 'Versión liviana y económica del Barros Luco: jamón pierna artesanal dorado en sartén con queso laminado derretido en pan tostado.',
    categoria: 'once',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 380,
      proteinas: 19,
      carbohidratos: 46,
      grasas: 13,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Jamón Pierna tradicional envasado', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pierna tradicional' },
      { nombre: 'Queso chanco o gouda laminado', cantidad: 15, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'queso chanco' },
    ],
    instrucciones: [
      'Tostar la marraqueta.',
      'Dorar el jamón pierna en la sartén 1 minuto y colocar la lámina de queso encima hasta que funda.',
      'Montar dentro de la marraqueta crujiente y servir caliente.',
    ],
  },
  {
    id: 'onc-03',
    nombre: 'Sánguche de Pasta Ave Palta Rápida en Pan Integral',
    descripcion: 'Pechuga de pollo dorada y picada con cuchillo, mezclada con palta en pan de molde integral tostado.',
    categoria: 'once',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 310,
      proteinas: 18,
      carbohidratos: 24,
      grasas: 13,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 50, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Palta Hass', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
    ],
    instrucciones: [
      'Dorar el filete de pollo en sartén 4 minutos y picarlo finito en la tabla.',
      'Moler la palta con tenedor en un plato con sal y mezclar con el pollo picado.',
      'Rellenar la tostada con la pasta ave palta.',
    ],
  },
  {
    id: 'onc-04',
    nombre: 'Tostadas con Quesillo Sureño y Tomate al Orégano',
    descripcion: 'Once liviana y fresca: pan tostado crujiente con láminas de quesillo fresco, tomate en rodajas y orégano.',
    categoria: 'once',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 240,
      proteinas: 14,
      carbohidratos: 36,
      grasas: 4,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la rebanada de pan.',
      'Montar el quesillo cortado en láminas y el tomate en rodajas.',
      'Espolvorear orégano seco y una pizca de sal.',
    ],
  },
  {
    id: 'onc-05',
    nombre: 'Sánguche de Pasta Ave Mayo Rápida con Mayonesa Kraft en Pan Integral',
    descripcion: 'Clásico chileno de once: pechuga de pollo desmenuzada con mayonesa Kraft cremosa en pan de molde integral tostado.',
    categoria: 'once',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 330,
      proteinas: 18,
      carbohidratos: 22,
      grasas: 18,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 50, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
    ],
    instrucciones: [
      'Dorar o cocer la pechuga de pollo 4 minutos y picarla fina en la tabla.',
      'Mezclar en un pocillo el pollo desmenuzado con 1 cucharada sopera de Mayonesa Kraft y pizca de sal.',
      'Tostar la rebanada de pan y untar con la pasta ave mayo bien cremosa.',
    ],
  },
  {
    id: 'onc-06',
    nombre: 'Tostadas con Palta y Tomate Fresco al Orégano',
    descripcion: 'Once clásica de verano: pan tostado crujiente con palta hass y tomate fresco aliñado con orégano.',
    categoria: 'once',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 240,
      proteinas: 6,
      carbohidratos: 26,
      grasas: 12,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Palta Hass', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la rebanada de pan integral.',
      'Moler la palta con sal sobre la tostada.',
      'Colocar rodajas de tomate y espolvorear orégano.',
    ],
  },
  {
    id: 'onc-07',
    nombre: 'Tazón de Leche Proteica con Cacao y Pan con Jamón Pierna',
    descripcion: 'La once reconfortante de toda la vida: tazón de leche proteica tibia con cacao amargo y pan tostado con jamón pierna.',
    categoria: 'once',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 280,
      proteinas: 22,
      carbohidratos: 36,
      grasas: 5,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 200, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein colun' },
      { nombre: 'Cacao amargo en polvo puro', cantidad: 5, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'cacao amargo' },
      { nombre: 'Jamón Pierna tradicional envasado', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pierna tradicional' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
    ],
    instrucciones: [
      'Calentar la leche proteica en taza al microondas por 1 minuto y disolver el cacao amargo.',
      'Tostar el pan y rellenar con las láminas de jamón pierna.',
    ],
  },
  {
    id: 'onc-08',
    nombre: 'Sándwich de Jamón de Pavo con Palta y Tomate en Pan Integral',
    descripcion: 'Sándwich fresco y rápido: pechuga de pavo con palta molida y rodajas de tomate en pan tostado.',
    categoria: 'once',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 270,
      proteinas: 14,
      carbohidratos: 28,
      grasas: 12,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Pechuga / Jamón de pavo', cantidad: 25, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pavo' },
      { nombre: 'Palta Hass', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
    ],
    instrucciones: [
      'Tostar la rebanada de pan integral.',
      'Untar la palta molida con una pizca de sal.',
      'Agregar las rodajas de tomate y las láminas de pavo.',
    ],
  },

  // ==========================================
  // CENAS (6) — LIGERAS, PROTEICAS Y NOCTURNAS (5 A 8 MINUTOS)
  // ==========================================
  {
    id: 'cen-01',
    nombre: 'Pote Liviano de Pollo Dorado con Ensalada Mix Toscana y Mayonesa Kraft',
    descripcion: 'Cena rápida y digestiva: dados de pechuga dorada con mix de ensalada toscana fresca y una cucharada de mayonesa Kraft.',
    categoria: 'cena',
    tiempoMinutos: 7,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: true,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 320,
      proteinas: 24,
      carbohidratos: 4,
      grasas: 20,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 75, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Mayonesa Regular Frasco, 1.262 g', cantidad: 15, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'mayonesa regular kraft frasco' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Dorar las tiras o dados de pollo en sartén con gotas de aceite, 2 minutos por lado.',
      'Servir junto a la porción de Ensalada Mix Toscana fresca.',
      'Coronar con 1 cucharada de Mayonesa Kraft.',
      '💡 Tip Batch Cooking: Puedes tener los dados de pollo dorados previamente en un pote y solo montarlo con la ensalada fresca en 1 minuto.',
    ],
  },
  {
    id: 'cen-02',
    nombre: 'Salteado de Champiñones y Zapallitos Italianos al Sartén con Tostada',
    descripcion: 'Cena vegetal liviana: champiñones laminados y zapallito italiano salteados con aceite de oliva y orégano sobre 1 tostada.',
    categoria: 'cena',
    tiempoMinutos: 7,
    porciones: 1,
    fuenteProteinaPrincipal: 'mixto',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 190,
      proteinas: 8,
      carbohidratos: 24,
      grasas: 7,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Champiñones laminados', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champiñones' },
      { nombre: 'Zapallito italiano', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo italiano' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Saltear los champiñones y el zapallito italiano en la sartén durante 4 minutos a fuego vivo.',
      'Tostar la rebanada de pan integral.',
      'Servir el salteado caliente sobre la tostada con orégano.',
    ],
  },
  {
    id: 'cen-03',
    nombre: 'Tostada Nocturna con Quesillo Sureño y Tomate al Orégano',
    descripcion: 'Cena ultra liviana para descansar sin pesadez: pan integral tostado con láminas de quesillo y tomate picado al orégano.',
    categoria: 'cena',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 180,
      proteinas: 11,
      carbohidratos: 22,
      grasas: 4,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Tomate chileno', cantidad: 0.5, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la rebanada de pan.',
      'Montar el quesillo cortado en láminas y el tomate en rodajas.',
      'Espolvorear con orégano y servir con una infusión o té caliente.',
    ],
  },
  {
    id: 'cen-04',
    nombre: 'Ensalada Tibia Express de Pollo Dorado con Palta y Ensalada Toscana',
    descripcion: 'Ensalada completa lista en 6 minutos: pechuga dorada en dados servida sobre mix de ensalada toscana fresca y palta.',
    categoria: 'cena',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 270,
      proteinas: 24,
      carbohidratos: 6,
      grasas: 16,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 75, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Ensalada Mix Toscana Bolsa, 180 g', cantidad: 70, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'ensalada toscana mix proverde' },
      { nombre: 'Palta Hass', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Saltear la pechuga en dados durante 4 minutos en sartén con gotas de aceite.',
      'Servir en un plato hondo sobre la porción de Ensalada Mix Toscana fresca.',
      'Agregar la palta en láminas con una pizca de sal y servir tibia.',
    ],
  },
  {
    id: 'cen-05',
    nombre: 'Tiras de Pollo al Ajo con Zapallitos Italianos al Sartén',
    descripcion: 'Una sola sartén, 7 minutos: pollo y zapallito en medias lunas salteados juntos con orégano y aceite de oliva.',
    categoria: 'cena',
    tiempoMinutos: 7,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 220,
      proteinas: 23,
      carbohidratos: 6,
      grasas: 9,
      fibra: 2.5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 75, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Zapallito italiano', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo italiano' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Cortar el zapallito italiano en rodajas delgadas o medias lunas.',
      'Saltear el pollo y el zapallito juntos a fuego medio-alto por 5 minutos hasta que doren.',
      'Sazonar con sal y servir caliente.',
    ],
  },
  {
    id: 'cen-06',
    nombre: 'Revuelto Nocturno de 1 Huevo con Queso Derretido y Tostada',
    descripcion: 'Cena rápida en 4 minutos: 1 huevo batido con cubitos de queso derretido en la sartén y servido sobre 1 tostada crujiente.',
    categoria: 'cena',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 280,
      proteinas: 15,
      carbohidratos: 18,
      grasas: 16,
      fibra: 2.5,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Queso chanco o gouda laminado', cantidad: 15, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'queso chanco' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan de molde integral' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Tostar la rebanada de pan integral.',
      'Batir el huevo y verter en sartén caliente con gotas de aceite y trozos de queso.',
      'Revolver 2 minutos con espátula a fuego medio hasta que unifique y funda el queso.',
      'Servir caliente sobre la tostada.',
    ],
  },
];
