import type { Receta } from '../types';

export const SEMILLAS_RECETAS: Receta[] = [
  // ==========================================
  // DESAYUNOS (8) — RÁPIDOS (5 A 10 MINUTOS)
  // ==========================================
  {
    id: 'des-01',
    nombre: 'Huevos Revueltos Express con Marraqueta y Palta',
    descripcion: 'Desayuno chileno clásico de 8 minutos: 4 huevos en sartén rápida, marraqueta crocante al tostador y palta fresca.',
    categoria: 'desayuno',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 34,
      carbohidratos: 48,
      grasas: 24,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos grandes' },
      { nombre: 'Claras de huevo', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'claras de huevo' },
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Palta Hass', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner la marraqueta en el tostador a fuego medio.',
      'Cascar 2 huevos enteros y 2 claras directo en la sartén caliente con unas gotas de aceite.',
      'Revolver con espátula a fuego medio solo 3 minutos hasta que cuajen tiernos.',
      'Moler la palta con tenedor en el plato con una pizca de sal, untar el pan y servir todo junto.',
    ],
  },
  {
    id: 'des-02',
    nombre: 'Bowl Express de Avena con Leche Proteica y Plátano al Tenedor',
    descripcion: 'Desayuno o pre-entreno listo en 2 minutos en un tazón: energía limpia, cero cocción y cero licuadora. Mezclar con cuchara y comer.',
    categoria: 'desayuno',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 30,
      carbohidratos: 84,
      grasas: 7,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 350, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Avena instantánea tradicional', cantidad: 70, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'canela molida' },
      { nombre: 'Miel de abeja', cantidad: 10, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'miel' },
    ],
    instrucciones: [
      'En un tazón o plato hondo, verter la leche con proteína y agregar la avena instantánea.',
      'Revolver 15 segundos con cuchara (se hidrata al instante con leche fría o tras 30s al microondas si la prefieres tibia).',
      'Cortar el plátano en rodajas con cuchillo por encima, espolvorear canela y disfrutar con cuchara.',
    ],
  },
  {
    id: 'des-03',
    nombre: 'Tostadas Rápidas con Quesillo Sureño y Jamón de Pavo',
    descripcion: 'Desayuno fresco sin sartenes listo en 4 minutos: pan tostado crujiente con abundante quesillo de Osorno y pechuga de pavo.',
    categoria: 'desayuno',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 450,
      proteinas: 40,
      carbohidratos: 46,
      grasas: 11,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral 100%', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 100, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Tomate chileno', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar las rebanadas de pan en tostador eléctrico o chileno.',
      'Cortar el quesillo y el tomate en láminas rápidas.',
      'Montar sobre el pan tostado el jamón de pavo, el quesillo y las rodajas de tomate.',
      'Espolvorear orégano seco y servir.',
    ],
  },
  {
    id: 'des-04',
    nombre: 'Omelette Express de 3 Huevos con Quesillo y Orégano',
    descripcion: 'Una sola sartén, 6 minutos de cocción total. Proteína pura compacta y digestiva.',
    categoria: 'desayuno',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 420,
      proteinas: 36,
      carbohidratos: 10,
      grasas: 24,
      fibra: 1,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos grandes' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 80, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano y sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Batir rápidamente los 3 huevos en un tazón con tenedor y una pizca de sal (30 segundos).',
      'Calentar la sartén con gotas de aceite y verter el huevo batido.',
      'Añadir los trozos de quesillo sobre una mitad y espolvorear orégano.',
      'Doblar el omelette por la mitad con espátula y retirar al plato.',
    ],
  },
  {
    id: 'des-05',
    nombre: 'Overnight Oats Express (Avena en Frasco de 1 Minuto)',
    descripcion: 'Se mezcla en 1 minuto la noche anterior y en la mañana solo se destapa y se come frío. Cero tiempo perdido en la mañana.',
    categoria: 'desayuno',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 480,
      proteinas: 36,
      carbohidratos: 66,
      grasas: 8,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 70, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Yogurt tipo griego natural protein', cantidad: 150, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Leche descremada con proteína', cantidad: 150, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Arándanos frescos o congelados', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'arandanos' },
    ],
    instrucciones: [
      'En un frasco o pote, mezclar con cuchara la avena, el yogurt griego y la leche con proteína.',
      'Tapar y guardar en el refrigerador durante la noche.',
      'Al despertar, destapar, poner los arándanos arriba y comer con cuchara directo del frasco.',
    ],
  },
  {
    id: 'des-06',
    nombre: 'Panqueques Express al Sartén (Moler al Tenedor)',
    descripcion: 'Se machaca el plátano con tenedor en 20 segundos, se baten los huevos con la avena y va directo al sartén en vitrocerámica. Cero licuadora.',
    categoria: 'desayuno',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 26,
      carbohidratos: 68,
      grasas: 12,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 60, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'En un plato hondo, moler el plátano con tenedor hasta hacerlo papilla suave (20 segundos).',
      'Romper los 2 huevos en el mismo plato, agregar la avena y la canela, y batir enérgicamente con el tenedor hasta unificar.',
      'Verter en un sartén antiadherente caliente con una gota de aceite (2 minutos por lado a fuego medio en la vitrocerámica) y servir.',
    ],
  },
  {
    id: 'des-07',
    nombre: 'Sándwich de Huevo Duro y Pechuga de Pavo en Marraqueta',
    descripcion: 'Rápido, contundente y tradicional. Si dejas huevos cocidos en el refrigerador, se arma en solo 2 minutos.',
    categoria: 'desayuno',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 510,
      proteinas: 42,
      carbohidratos: 52,
      grasas: 13,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Huevo duro', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
    ],
    instrucciones: [
      'Tostar la marraqueta.',
      'Picar los huevos duros en rodajas con cuchillo.',
      'Rellenar el pan tostado con las láminas de pavo y el huevo en rodajas.',
    ],
  },
  {
    id: 'des-08',
    nombre: 'Tazón de Avena Instantánea con Leche Proteica al Microondas',
    descripcion: 'Listo en 2 minutos: calientas la leche con avena al microondas, revuelves y decoras con fruta.',
    categoria: 'desayuno',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 470,
      proteinas: 28,
      carbohidratos: 75,
      grasas: 7,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 70, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Leche descremada con proteína', cantidad: 300, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela molida', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'En un tazón hondo apto para microondas, poner la avena y la leche con proteína.',
      'Calentar a potencia alta durante 1 minuto y 30 segundos.',
      'Revolver con cuchara (queda cremoso de inmediato) y poner rodajas de plátano encima.',
    ],
  },

  // ==========================================
  // ALMUERZOS (12) — FÁCILES & RÁPIDOS (10 A 15 MIN)
  // ==========================================
  {
    id: 'alm-01',
    nombre: 'Sartén Express de Pechuga Fileteada con Arroz Blanco y Tomate',
    descripcion: 'El rey de la comida de gym: filetes finos de pechuga que se doran en 6 minutos, servidos con arroz y tomate fresco.',
    categoria: 'almuerzo',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 660,
      proteinas: 58,
      carbohidratos: 72,
      grasas: 14,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada fileteada', cantidad: 250, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo deshuesada' },
      { nombre: 'Arroz blanco grado 1 (cocido o listo)', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Tomate chileno', cantidad: 150, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Ajo en polvo y sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar la sartén a fuego alto con un toque de aceite de oliva.',
      'Sazonar los filetes de pechuga con sal y ajo en polvo.',
      'Sellar 3 minutos por lado en la sartén hasta que estén dorados y jugosos.',
      'Servir junto al arroz tibio y el tomate cortado en gajos con sal.',
    ],
  },
  {
    id: 'alm-02',
    nombre: 'Hamburguesas Caseras de Vacuno Magro con Papas al Microondas',
    descripcion: 'Papas cocidas al microondas en 7 minutos y dos hamburguesas de tártaro 4% grasa vuelta y vuelta en sartén.',
    categoria: 'almuerzo',
    tiempoMinutos: 15,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 640,
      proteinas: 54,
      carbohidratos: 62,
      grasas: 16,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Posta negra molida magra (tártaro 4% grasa)', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra tartaro' },
      { nombre: 'Papas granel lavadas', cantidad: 250, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas granel' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal de mar y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Lavar las papas, pinchar con tenedor y meter al microondas en plato hondo durante 6 a 7 minutos hasta que estén blandas.',
      'Formar 2 hamburguesas aplastando la carne con las manos y sazonar con sal y orégano.',
      'Dorar en sartén bien caliente 2 a 3 minutos por lado.',
      'Abrir las papas por la mitad, rociar con aceite de oliva y servir con las hamburguesas.',
    ],
  },
  {
    id: 'alm-03',
    nombre: 'Crudo Rápido de Posta Negra (Tártaro Sureño) con Tostadas',
    descripcion: 'Cero minutos de fuego: posta fresca extra magra con jugo de limón exprimido, cebollín y tostadas integrales.',
    categoria: 'almuerzo',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 54,
      carbohidratos: 44,
      grasas: 12,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Posta negra molida magra (tártaro o picada)', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra tartaro' },
      { nombre: 'Pan de molde integral 100%', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Limón fresco', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
      { nombre: 'Cebolla o cebollín picado fino', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'cebollin' },
      { nombre: 'Aceite de oliva y sal', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner la posta en un bol hondo con la sal y la cebolla picada.',
      'Exprimir el jugo de limón y revolver con tenedor 30 segundos.',
      'Tostar el pan integral y servir la carne fría encima de las tostadas.',
    ],
  },
  {
    id: 'alm-04',
    nombre: 'Arroz Chaufa Universitario Fit de Pollo y Huevo',
    descripcion: 'Todo en un solo sartén: pollo en cubos, huevo revuelto y arroz blanco salteados en 10 minutos.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 680,
      proteinas: 56,
      carbohidratos: 74,
      grasas: 16,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada en tiritas', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Arroz blanco grado 1 cocido', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Cebollín picado', cantidad: 30, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'cebollin' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'En una sartén caliente con aceite, dorar las tiras de pollo sazonadas por 4 minutos.',
      'Empujar el pollo a un lado de la sartén, quebrar los 2 huevos y revolverlos 1 minuto.',
      'Tirar el arroz cocido y el cebollín, revolver todo a fuego alto por 2 minutos y listo.',
    ],
  },
  {
    id: 'alm-05',
    nombre: 'Filete de Salmón Sureño a la Plancha con Puré Instantáneo',
    descripcion: 'Salmón sellado vuelta y vuelta 6 minutos y puré de papas que se hidrata con agua hirviendo en 2 minutos.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 650,
      proteinas: 46,
      carbohidratos: 52,
      grasas: 24,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Filete de salmón fresco o congelado', cantidad: 200, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'salmon porciones' },
      { nombre: 'Papas en escamas para puré instantáneo', cantidad: 60, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'pure papas' },
      { nombre: 'Leche descremada', cantidad: 100, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche descremada' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal y limón', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'En un tazón mezclar las escamas de puré con 150 ml de agua hirviendo y la leche con sal (listo en 1 minuto).',
      'Poner el salmón sazonado con sal en sartén bien caliente: 3 minutos por lado.',
      'Servir el salmón bañado en jugo de limón junto al puré.',
    ],
  },
  {
    id: 'alm-06',
    nombre: 'Bistec de Posta Negra a la Plancha con Arroz y Ensalada de Tomate',
    descripcion: 'Corte magro y rápido: el bistec de posta está listo en 4 minutos en sartén de hierro bien caliente.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 630,
      proteinas: 54,
      carbohidratos: 68,
      grasas: 15,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Posta negra bistec magro', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra bistec' },
      { nombre: 'Arroz blanco cocido', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Tomate chileno', cantidad: 150, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar la sartén a fuego máximo con unas gotas de aceite.',
      'Poner el bistec con sal marina: 2 minutos por lado para que quede tierno y jugoso.',
      'Cortar el tomate en cuartos y servir al plato junto con el arroz.',
    ],
  },
  {
    id: 'alm-07',
    nombre: 'Tallarines con Atún al Agua y Salsa de Tomate Natural (1 Olla)',
    descripcion: 'Hervir fideos 8 minutos, tirar la salsa de tomate y el atún escurrido. Sin ensuciar nada más.',
    categoria: 'almuerzo',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 650,
      proteinas: 52,
      carbohidratos: 85,
      grasas: 10,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Fideos spaghetti o tallarines', cantidad: 90, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'tallarines' },
      { nombre: 'Lomitos de atún al agua en conserva', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Salsa de tomate natural o passata sin azúcar', cantidad: 150, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'salsa de tomate' },
      { nombre: 'Aceite de oliva y orégano', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Hervir los tallarines en agua con sal durante 8 minutos y escurrir el agua.',
      'En la misma olla caliente, verter la salsa de tomate, el atún escurrido, aceite de oliva y orégano.',
      'Revolver 1 minuto a fuego suave y servir caliente.',
    ],
  },
  {
    id: 'alm-08',
    nombre: 'Bistec de Lomo de Cerdo al Sartén con Palta y Arroz',
    descripcion: 'El lomo centro de cerdo es económico, ultra magro y se cocina en 6 minutos a la plancha.',
    categoria: 'almuerzo',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 640,
      proteinas: 52,
      carbohidratos: 65,
      grasas: 18,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Lomo centro de cerdo magro fileteado', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'lomo centro cerdo' },
      { nombre: 'Arroz blanco cocido', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Palta Hass en láminas', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar la sartén con gotas de aceite.',
      'Sellar el lomo de cerdo con sal y orégano durante 3 minutos por lado.',
      'Servir con el arroz caliente y la palta cortada en rodajas.',
    ],
  },
  {
    id: 'alm-09',
    nombre: 'Salteado Express de Carne Molida Magra con Arroz y Huevo a la Copa',
    descripcion: 'Pino rápido de tártaro dorado 5 minutos, servido sobre arroz caliente con huevo frito en agua/gotas de aceite.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 670,
      proteinas: 56,
      carbohidratos: 68,
      grasas: 17,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Posta negra molida tártaro 4% grasa', cantidad: 220, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra tartaro' },
      { nombre: 'Arroz blanco cocido', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Huevo de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Comino y sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Dorar la carne molida en la sartén con sal y pizca de comino durante 4 minutos.',
      'Retirar la carne y en la misma sartén cocinar el huevo 2 minutos.',
      'Montar el arroz, la carne molida y coronar con el huevo.',
    ],
  },
  {
    id: 'alm-10',
    nombre: 'Merluza Austral en Sartén con Papas al Microondas y Limón',
    descripcion: 'Pescado blanco rápido: se cocina en solo 6 minutos en sartén, acompañado de papas cocidas al microondas.',
    categoria: 'almuerzo',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 48,
      carbohidratos: 56,
      grasas: 10,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Filete de merluza austral fresca o descongelada', cantidad: 250, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'merluza filete' },
      { nombre: 'Papas granel lavadas', cantidad: 220, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas granel' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Limón y sal de mar', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Pinchar las papas y cocinarlas al microondas 6 minutos en un plato hondo.',
      'Cocinar el filete de merluza en sartén con gotas de aceite y sal 3 minutos por lado.',
      'Rociar abundante limón y servir con las papas calientes.',
    ],
  },
  {
    id: 'alm-11',
    nombre: 'Fajitas / Wraps Rápidos de Pollo con Palta y Tomate',
    descripcion: 'Tiras de pollo doradas en 6 minutos envueltas en tortillas integrales con palta y tomate en cubos.',
    categoria: 'almuerzo',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 620,
      proteinas: 54,
      carbohidratos: 52,
      grasas: 18,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada en tiritas', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Tortillas de trigo integrales (rapiditas)', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'tortillas integrales' },
      { nombre: 'Palta Hass molida', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Tomate en cubitos', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva y sal', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Dorar el pollo sazonado con sal en sartén caliente durante 5 minutos.',
      'Calentar las tortillas 20 segundos en el tostador o sartén.',
      'Untar la palta en las tortillas, colocar el pollo caliente y los cubos de tomate, enrollar y comer con las manos.',
    ],
  },
  {
    id: 'alm-12',
    nombre: 'Wok Rápido de Pechuga de Pavo con Fideos y Champiñones',
    descripcion: 'Pavo salteado a fuego fuerte con champiñones listos y fideos al dente. Sabroso, magro y en 12 minutos.',
    categoria: 'almuerzo',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 610,
      proteinas: 56,
      carbohidratos: 68,
      grasas: 12,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pavo fileteada cortada en tiras', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga de pavo' },
      { nombre: 'Fideos spaghetti cocidos', cantidad: 180, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'tallarines' },
      { nombre: 'Champiñones laminados', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champinones' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Dorar el pavo y los champiñones en sartén caliente con aceite por 5 minutos.',
      'Añadir los fideos cocidos y mezclar todo en la misma sartén 2 minutos.',
      'Servir de inmediato.',
    ],
  },

  // ==========================================
  // COLACIONES (6) — INSTANTÁNEAS (1 A 3 MIN)
  // ==========================================
  {
    id: 'col-01',
    nombre: 'Yogurt Griego Protein con Plátano en Rodajas',
    descripcion: 'Destapar el yogurt, cortar un plátano en 30 segundos y listo. 22g de proteína pura.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 280,
      proteinas: 22,
      carbohidratos: 38,
      grasas: 2,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Yogurt Protein natural o saborizado sin azúcar', cantidad: 200, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
    ],
    instrucciones: [
      'Vaciar el yogurt en un pocillo.',
      'Pelar el plátano, cortarlo en rodajas con cuchillo y mezclar.',
    ],
  },
  {
    id: 'col-02',
    nombre: 'Lata de Atún al Agua con Limón y Galletas Integrales',
    descripcion: 'Abre fácil: atún directo de la lata con limón y galletas de agua. Cero cocina, 32g de proteína.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 250,
      proteinas: 32,
      carbohidratos: 22,
      grasas: 3,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Lomitos de atún al agua en conserva', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua lomo' },
      { nombre: 'Galletas de agua integrales o de salvado', cantidad: 5, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'galletas de agua' },
      { nombre: 'Limón y pimienta', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Escurrir el agua de la lata.',
      'Echar un chorro de limón directo adentro de la lata con pimienta.',
      'Comer montando sobre las galletas integrales.',
    ],
  },
  {
    id: 'col-03',
    nombre: 'Rollitos de Pechuga de Pavo con Quesillo Fresco',
    descripcion: 'Enrollar el quesillo dentro de las láminas de pavo. Listo en 90 segundos.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 230,
      proteinas: 28,
      carbohidratos: 4,
      grasas: 10,
      fibra: 1,
    },
    ingredientes: [
      { nombre: 'Jamón de pechuga de pavo acaramelado o cocido', cantidad: 100, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon de pavo' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 70, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Cortar bastones de quesillo.',
      'Enrollar cada bastón con una rebanada de jamón de pavo.',
      'Comer directo con las manos.',
    ],
  },
  {
    id: 'col-04',
    nombre: 'Leche Proteica Helada con Plátano al Paso',
    descripcion: 'El post-entreno más rápido del mundo: abres la caja de leche protein Colun y la acompañas con un plátano entero. Cero cocina, cero aparatos.',
    categoria: 'colacion',
    tiempoMinutos: 1,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 300,
      proteinas: 26,
      carbohidratos: 44,
      grasas: 2,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 300, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
    ],
    instrucciones: [
      'Servir la leche con proteína bien fría en un vaso (o beber directo del envase individual).',
      'Pelar el plátano y comerlo junto con la leche para recuperación muscular inmediata.',
    ],
  },
  {
    id: 'col-05',
    nombre: 'Huevos Duros Cocidos en Lote con Sal de Mar',
    descripcion: 'Cocinas 6 huevos el domingo en 9 minutos y tienes colaciones de 15g de proteína listas para toda la semana.',
    categoria: 'colacion',
    tiempoMinutos: 1,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 6,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 150,
      proteinas: 14,
      carbohidratos: 1,
      grasas: 10,
      fibra: 0,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Sal de mar', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Sacar 2 huevos duros ya cocidos del refrigerador.',
      'Pelar bajo agua corriente, poner pizca de sal y comer.',
    ],
  },
  {
    id: 'col-06',
    nombre: 'Manzana Verde en Gajos con Queso Ricotta Magro',
    descripcion: 'Crujiente, fresco y sin prender fuego. 14g de proteína.',
    categoria: 'colacion',
    tiempoMinutos: 2,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 230,
      proteinas: 14,
      carbohidratos: 32,
      grasas: 4,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Manzana verde granny smith', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'manzana verde' },
      { nombre: 'Queso ricotta magro', cantidad: 90, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'ricotta' },
    ],
    instrucciones: [
      'Cortar la manzana en gajos.',
      'Untar cada trozo en la ricotta y comer.',
    ],
  },

  // ==========================================
  // ONCE CHILENA (8) — RÁPIDAS (5 A 8 MIN)
  // ==========================================
  {
    id: 'onc-01',
    nombre: 'Once Chilena Tradicional: Marraqueta con Palta y 2 Huevos',
    descripcion: 'El clásico chileno definitivo de 6 minutos: pan tostado, palta molida y 2 huevos al sartén rápido más taza de té.',
    categoria: 'once',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 470,
      proteinas: 24,
      carbohidratos: 46,
      grasas: 22,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Palta Hass molida', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Bolsita de té negro ceilán', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'bebidas', opcional: false, terminoBusquedaLider: 'te negro' },
      { nombre: 'Sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la marraqueta y poner el hervidor de agua para el té.',
      'Revolver los 2 huevos 2 minutos en sartén con pizca de sal.',
      'Moler la palta con tenedor en el pan tostado y montar los huevos encima.',
    ],
  },
  {
    id: 'onc-02',
    nombre: 'Barros Luco Express de Posta Negra en Marraqueta',
    descripcion: 'Láminas finas de posta negra selladas 1 minuto por lado con queso derretido en la misma sartén. 50g de proteína.',
    categoria: 'once',
    tiempoMinutos: 7,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 50,
      carbohidratos: 48,
      grasas: 18,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Posta negra en láminas delgadas (bistec)', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Queso chanco o gouda laminado', cantidad: 40, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'queso chanco laminado' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal marina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la marraqueta.',
      'Sellar la posta negra en sartén a fuego alto 1 minuto por lado con sal.',
      'Poner las láminas de queso sobre la carne en la sartén y tapar 20 segundos para que funda.',
      'Meter todo al pan crujiente y servir.',
    ],
  },
  {
    id: 'onc-03',
    nombre: 'Sánguche de Pasta Ave Palta Rápida en Marraqueta',
    descripcion: 'Pechuga de pollo cocida desmenuzada mezclada con palta y una cucharadita de yogurt natural. Cero fritura.',
    categoria: 'once',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 48,
      carbohidratos: 46,
      grasas: 16,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo cocida y desmenuzada', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Palta Hass molida', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Yogurt natural descremado sin azúcar', cantidad: 25, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: true, terminoBusquedaLider: 'yogurt natural' },
      { nombre: 'Sal y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'En un bol mezclar el pollo con la palta molida, pizca de sal y la cucharada de yogurt.',
      'Tostar la marraqueta y rellenar con la pasta ave palta.',
    ],
  },
  {
    id: 'onc-04',
    nombre: 'Tostadas con Abundante Quesillo Sureño y Tomate al Orégano',
    descripcion: 'La once sureña más rápida: 3 minutos, fresca, digestiva y con 28g de proteína.',
    categoria: 'once',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 390,
      proteinas: 28,
      carbohidratos: 44,
      grasas: 11,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral 100%', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 140, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Tomate chileno en rodajas', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva virgen', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar el pan integral.',
      'Cubrir con rodajas gruesas de quesillo de Osorno y tomate.',
      'Echar un hilo de aceite de oliva y orégano encima.',
    ],
  },
  {
    id: 'onc-05',
    nombre: 'Paila Express de Huevos con Jamón de Pavo',
    descripcion: 'Dorar el pavo 1 minuto en sartén pequeña, cascar 3 huevos arriba y tapar 3 minutos. Listo.',
    categoria: 'once',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 360,
      proteinas: 38,
      carbohidratos: 5,
      grasas: 20,
      fibra: 1,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 70, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano seco', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner el jamón de pavo picado en sartén con gotas de aceite 1 minuto.',
      'Cascar los 3 huevos encima, poner sal y orégano.',
      'Bajar a fuego suave y tapar 2 a 3 minutos hasta que la clara cuaje. Comer directo de la sartén.',
    ],
  },
  {
    id: 'onc-06',
    nombre: 'Sánguche Rápido de Atún con Huevo Duro en Marraqueta',
    descripcion: 'Mezclar atún de lata escurrido con un huevo duro picado en 1 minuto. Súper saciante.',
    categoria: 'once',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 44,
      carbohidratos: 48,
      grasas: 12,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Lomitos de atún al agua en conserva', cantidad: 120, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Huevo duro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Gotas de limón o aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Tostar la marraqueta.',
      'Mezclar en un plato el atún escurrido con el huevo duro picado y unas gotas de limón o aceite de oliva.',
      'Rellenar el pan tostado y servir.',
    ],
  },
  {
    id: 'onc-07',
    nombre: 'Tazón de Leche Proteica con Cacao y Pan con Jamón de Pavo',
    descripcion: 'Calentar la leche en microondas 1 minuto con cacao puro, acompañado de pan tostado con pavo.',
    categoria: 'once',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 450,
      proteinas: 36,
      carbohidratos: 56,
      grasas: 8,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína', cantidad: 300, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Cacao amargo en polvo puro', cantidad: 10, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'cacao amargo en polvo' },
      { nombre: 'Pan de molde integral', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 60, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
    ],
    instrucciones: [
      'Calentar la leche en el microondas 1 minuto y revolver con el cacao en polvo.',
      'Tostar las rebanadas de pan y rellenar con el jamón de pavo.',
    ],
  },
  {
    id: 'onc-08',
    nombre: 'Sandwich de Posta en Marraqueta con Tomate y Ají Verde',
    descripcion: 'Sellar bistec fino de posta 2 minutos, meter a la marraqueta con rodajas de tomate y ají verde fresco.',
    categoria: 'once',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 510,
      proteinas: 46,
      carbohidratos: 48,
      grasas: 13,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Posta negra en láminas delgadas', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Tomate chileno en rodajas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Ají verde fresco en tiritas', cantidad: 15, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'aji verde' },
      { nombre: 'Aceite de oliva y sal', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar la marraqueta.',
      'Sellar las láminas de posta en sartén caliente 1 minuto por lado con sal.',
      'Montar la carne en el pan junto al tomate en rodajas y tiritas de ají verde.',
    ],
  },

  // ==========================================
  // CENAS (6) — LIVIANAS, RÁPIDAS & DIGESTIVAS (6 A 12 MIN)
  // ==========================================
  {
    id: 'cen-01',
    nombre: 'Filete de Merluza al Sartén con Espinacas Baby y Limón',
    descripcion: 'Pescado blanco rápido en 8 minutos: se dora en sartén y las espinacas se tiran al final 1 minuto.',
    categoria: 'cena',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 440,
      proteinas: 48,
      carbohidratos: 22,
      grasas: 12,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Filete de merluza austral fresca o descongelada', cantidad: 250, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'merluza filete' },
      { nombre: 'Espinacas baby lavadas', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'espinaca' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Limón y sal de mar', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Calentar la sartén con aceite y dorar la merluza con sal 3 minutos por lado.',
      'Tirar las espinacas baby en la misma sartén 1 minuto hasta que reduzcan.',
      'Rociar limón y acompañar con 1 rebanada de pan tostado.',
    ],
  },
  {
    id: 'cen-02',
    nombre: 'Sartén de Carne Molida Magra con Champiñones y Tostadas',
    descripcion: 'Tártaro 4% grasa salteado con champiñones laminados listos. Cero grasa pesada para dormir bien.',
    categoria: 'cena',
    tiempoMinutos: 9,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 480,
      proteinas: 52,
      carbohidratos: 32,
      grasas: 14,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Posta negra molida tártaro 4% grasa', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra tartaro' },
      { nombre: 'Champiñones laminados', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champinones' },
      { nombre: 'Pan de molde integral', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano y sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Saltear los champiñones y la carne molida magra en sartén con aceite, orégano y sal por 6 minutos.',
      'Tostar las 2 rebanadas de pan integral.',
      'Servir el salteado sobre las tostadas crocantes.',
    ],
  },
  {
    id: 'cen-03',
    nombre: 'Omelette Nocturno de Claras con Quesillo y Tomate',
    descripcion: '4 claras y 1 huevo entero cuajados en 5 minutos con quesillo fresco derretido.',
    categoria: 'cena',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 380,
      proteinas: 38,
      carbohidratos: 14,
      grasas: 16,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Claras de huevo', cantidad: 4, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'claras de huevo' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 90, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Tomate en rodajas', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Batir el huevo con las 4 claras y una pizca de sal 20 segundos.',
      'Verter en sartén con aceite, poner el quesillo en láminas y el tomate.',
      'Doblar el omelette y retirar a los 4 minutos.',
    ],
  },
  {
    id: 'cen-04',
    nombre: 'Ensalada Tibia Express de Pollo Dorado, Palta y Quesillo',
    descripcion: 'Sellar filetes de pollo 5 minutos y tirar sobre espinacas, palta y dados de quesillo. Cero platos sucios.',
    categoria: 'cena',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 54,
      carbohidratos: 12,
      grasas: 22,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada fileteada', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Espinacas baby lavadas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'espinaca' },
      { nombre: 'Palta Hass en cubos', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Quesillo sureño en dados', cantidad: 60, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Aceite de oliva y limón', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Dorar el pollo fileteado con sal en sartén caliente 5 minutos y cortar en tiras.',
      'En un bol poner las espinacas baby, la palta, el quesillo y el pollo tibio.',
      'Aliñar con jugo de limón y aceite de oliva.',
    ],
  },
  {
    id: 'cen-05',
    nombre: 'Tiras de Pollo al Ajo con Zapallitos Italianos al Sartén',
    descripcion: 'Pollo y zapallitos cortados en rodajas cocinados juntos en la misma sartén en 10 minutos.',
    categoria: 'cena',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 460,
      proteinas: 54,
      carbohidratos: 16,
      grasas: 16,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada en tiritas', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Zapallito italiano en rodajas', cantidad: 180, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallito italiano' },
      { nombre: 'Aceite de oliva virgen', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Ajo en polvo y sal', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Echar el pollo y los zapallitos juntos a la sartén bien caliente con aceite y ajo.',
      'Saltear a fuego vivo 6 a 7 minutos hasta que el pollo dore y las verduras queden tiernas.',
      'Servir directamente al plato.',
    ],
  },
  {
    id: 'cen-06',
    nombre: 'Revuelto Rápido de Atún y 3 Huevos con Tostada Integral',
    descripcion: 'Tirar la lata de atún escurrida y 3 huevos a la sartén. 3 minutos de cocina, 46g de proteína.',
    categoria: 'cena',
    tiempoMinutos: 6,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 460,
      proteinas: 46,
      carbohidratos: 24,
      grasas: 18,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Lomitos de atún al agua en conserva', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Huevos de gallina', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Aceite de oliva y orégano', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Tostar la rebanada de pan.',
      'En sartén caliente con gotas de aceite, echar el atún escurrido y cascar los 3 huevos.',
      'Revolver 2 minutos con espátula hasta que cuaje cremoso con orégano y sal.',
      'Servir con la tostada.',
    ],
  },
];
