import type { Receta } from '../types';

export const SEMILLAS_RECETAS: Receta[] = [
  // ==========================================
  // DESAYUNOS (8)
  // ==========================================
  {
    id: 'des-01',
    nombre: 'Huevos Revueltos con Marraqueta Tostada y Palta',
    descripcion: 'Clásico desayuno chileno alto en proteína con 4 huevos (2 enteros + 2 claras), marraqueta crujiente y palta fresca.',
    categoria: 'desayuno',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 34,
      carbohidratos: 48,
      grasas: 24,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos grandes' },
      { nombre: 'Claras de huevo', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'claras de huevo' },
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Palta Hass', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Batir los dos huevos enteros y las dos claras en un bol con pizca de sal.',
      'Calentar una sartén antiadherente con unas gotas de aceite de oliva a fuego medio.',
      'Verter la mezcla de huevos y revolver suavemente con espátula hasta lograr una textura cremosa.',
      'Tostar la marraqueta en tostador chileno y untar con la palta molida.',
      'Servir caliente.',
    ],
  },
  {
    id: 'des-02',
    nombre: 'Porridge de Avena Gym con Plátano y Canela',
    descripcion: 'Avena cocida cremosa con leche descremada, plátano en rodajas, canela molida y toque de miel.',
    categoria: 'desayuno',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 540,
      proteinas: 28,
      carbohidratos: 88,
      grasas: 8,
      fibra: 9,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 80, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 300, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'canela molida' },
      { nombre: 'Miel de abeja', cantidad: 10, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'miel' },
    ],
    instrucciones: [
      'Colocar la avena y la leche con proteína en una olla pequeña a fuego medio.',
      'Revolver constantemente durante 4 a 5 minutos hasta que espese y adquiera textura aterciopelada.',
      'Servir en un tazón hondo.',
      'Decorar con el plátano cortado en rodajas, espolvorear canela y añadir un hilo de miel.',
    ],
  },
  {
    id: 'des-03',
    nombre: 'Omelette de Quesillo Sureño y Jamón de Pavo',
    descripcion: 'Omelette dorado de 3 huevos con trozos de quesillo de Osorno y jamón de pechuga de pavo acaramelado.',
    categoria: 'desayuno',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 440,
      proteinas: 42,
      carbohidratos: 12,
      grasas: 24,
      fibra: 1,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos grandes' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 80, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 60, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Batir los 3 huevos con una pizca de sal y orégano en un recipiente.',
      'Calentar la sartén antiadherente con el aceite de oliva a fuego medio-bajo.',
      'Verter los huevos batidos cubriendo toda la base.',
      'Cuando la base cuaje pero la superficie siga húmeda, disponer el quesillo en láminas y el jamón picado en una mitad.',
      'Doblar el omelette por la mitad y cocinar 1 minuto más hasta que el quesillo entibie.',
    ],
  },
  {
    id: 'des-04',
    nombre: 'Panqueques de Avena, Plátano y Ricotta',
    descripcion: 'Torre de panqueques suaves y esponjosos hechos con avena molida, plátano maduro y queso ricotta magro.',
    categoria: 'desayuno',
    tiempoMinutos: 15,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 510,
      proteinas: 32,
      carbohidratos: 68,
      grasas: 12,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 60, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Queso ricotta o quesillo molido', cantidad: 70, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'ricotta' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Esencia de vainilla', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Licuar la avena, los huevos, el plátano, la ricotta y la vainilla hasta obtener una masa homogénea espesa.',
      'Calentar una sartén a fuego medio con unas gotas de aceite o rocío antiadherente.',
      'Verter porciones de masa para formar panqueques de unos 10 cm de diámetro.',
      'Cocinar 2 minutos por lado hasta que aparezcan burbujas y voltear con espátula.',
      'Servir en torre caliente.',
    ],
  },
  {
    id: 'des-05',
    nombre: 'Tostadas Integrales con Ricotta, Huevo Poché y Tomate',
    descripcion: 'Pan de molde grano entero tostado con abundante ricotta spread, rodajas de tomate y huevos poché.',
    categoria: 'desayuno',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 470,
      proteinas: 35,
      carbohidratos: 44,
      grasas: 16,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pan de molde integral 100%', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Queso ricotta magro', cantidad: 80, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'ricotta' },
      { nombre: 'Tomate maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Orégano y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Hervir agua en una olla con un chorrito de vinagre.',
      'Crear un remolino suave y soltar los huevos para pocharlos durante 3 minutos exactos.',
      'Tostar las rebanadas de pan integral.',
      'Untar la ricotta generosamente sobre el pan, colocar rodajas de tomate y montar los huevos poché encima.',
      'Espolvorear orégano fresco y pimienta negra molida.',
    ],
  },
  {
    id: 'des-06',
    nombre: 'Bowl de Avena Fría Nocturna (Overnight Oats) con Berries',
    descripcion: 'Avena remojada en leche alta en proteína y yogurt natural griego con arándanos y frutillas del sur.',
    categoria: 'desayuno',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 480,
      proteinas: 36,
      carbohidratos: 66,
      grasas: 8,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Avena instantánea tradicional', cantidad: 70, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Yogurt tipo griego natural protein', cantidad: 150, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Leche descremada con proteína', cantidad: 150, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Arándanos frescos o congelados', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'arandanos' },
      { nombre: 'Semillas de chía', cantidad: 10, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'semillas chia' },
    ],
    instrucciones: [
      'Mezclar en un frasco de vidrio la avena, el yogurt griego, la leche y las semillas de chía.',
      'Tapar y refrigerar durante toda la noche (mínimo 4 horas).',
      'A la mañana siguiente revolver bien y cubrir con los arándanos frescos.',
      'Consumir frío directo del frasco.',
    ],
  },
  {
    id: 'des-07',
    nombre: 'Sandwich de Pavo Asado, Huevo Cocido y Quesillo en Marraqueta',
    descripcion: 'Poderoso sandwich tradicional chileno con pechuga de pavo horneada en láminas, huevo duro y quesillo fresco.',
    categoria: 'desayuno',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 44,
      carbohidratos: 52,
      grasas: 14,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Pechuga de pavo cocida o jamón de pavo acaramelado', cantidad: 80, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pavo' },
      { nombre: 'Huevo duro', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 50, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Mostaza dijon o clásica', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'mostaza' },
    ],
    instrucciones: [
      'Tostar la marraqueta ligeramente para que esté crocante por fuera.',
      'Picar los huevos duros en rodajas parejas.',
      'Untar la marraqueta con un toque fino de mostaza.',
      'Rellenar con las láminas de pavo, el quesillo y los huevos cocidos.',
    ],
  },
  {
    id: 'des-08',
    nombre: 'Revuelto de Claras, Champiñones Salteados y Hallulla Integral',
    descripcion: 'Revuelto voluminoso de 4 claras y 1 huevo entero con champiñones salteados al orégano y media hallulla tostada.',
    categoria: 'desayuno',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 410,
      proteinas: 36,
      carbohidratos: 38,
      grasas: 12,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Claras de huevo', cantidad: 4, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'claras de huevo' },
      { nombre: 'Champiñones parís frescos', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champinones' },
      { nombre: 'Hallulla integral', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'hallulla integral' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Laminar los champiñones y saltearlos en una sartén con aceite de oliva por 3 minutos hasta dorar.',
      'Agregar las claras y el huevo batidos con pizca de sal y pimienta.',
      'Cocinar revolviendo suavemente hasta que esté tierno y jugoso.',
      'Acompañar con la hallulla integral tostada.',
    ],
  },

  // ==========================================
  // ALMUERZOS (12)
  // ==========================================
  {
    id: 'alm-01',
    nombre: 'Pechuga de Pollo a la Plancha con Puré Rústico de Papas y Ensalada Chilena',
    descripcion: 'Pechuga jugosa marinada en ajo y limón, servida con puré rústico con cáscara y ensalada chilena de tomate y cebolla amortiguada.',
    categoria: 'almuerzo',
    tiempoMinutos: 25,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 680,
      proteinas: 58,
      carbohidratos: 64,
      grasas: 18,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada', cantidad: 250, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo deshuesada' },
      { nombre: 'Papas medianas lavadas', cantidad: 250, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas granel' },
      { nombre: 'Leche descremada', cantidad: 50, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche descremada' },
      { nombre: 'Tomate chileno', cantidad: 150, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Cebolla blanca', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Cilantro fresco', cantidad: 10, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'cilantro' },
      { nombre: 'Aceite de oliva', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Hervir las papas con cáscara en agua con sal durante 20 minutos hasta que estén tiernas. Moler con pisapapas agregando la leche tibia y sal.',
      'Sazonar la pechuga de pollo con ajo, sal y pimienta. Dorar en plancha bien caliente 6 minutos por lado hasta que esté bien cocida y dorada.',
      'Cortar el tomate en gajos y la cebolla en pluma fina (amortiguada con sal y agua tibia). Mezclar con cilantro y gotas de aceite de oliva.',
      'Servir la pechuga junto al puré rústico humeante y la ensalada chilena.',
    ],
  },
  {
    id: 'alm-02',
    nombre: 'Carbonada Magra Criolla con Posta Negra y Zapallo Camote',
    descripcion: 'Guiso tradicional chileno preparado con cubos de posta negra desgrasada, zapallo camote, zanahoria, choclo desgranado y papas.',
    categoria: 'almuerzo',
    tiempoMinutos: 35,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 4,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 620,
      proteinas: 52,
      carbohidratos: 68,
      grasas: 14,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Posta negra de vacuno magra picada en cubos', cantidad: 220, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Zapallo camote en cubos', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo camote' },
      { nombre: 'Papas picadas en cubitos', cantidad: 150, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Zanahoria en cubitos', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zanahoria' },
      { nombre: 'Choclo desgranado congelado', cantidad: 60, unidad: 'g', categoriaPasillo: 'congelados', opcional: false, terminoBusquedaLider: 'choclo desgranado' },
      { nombre: 'Cebolla picada en brunoise', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Caldo de carne o verduras desgrasado', cantidad: 300, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'En una olla grande calentar el aceite y dorar la posta negra en cubitos a fuego vivo.',
      'Agregar la cebolla picada y sofreír por 4 minutos.',
      'Incorporar las papas, el zapallo camote, la zanahoria y el choclo.',
      'Cubrir con caldo hirviendo, agregar orégano, comino chileno y sal.',
      'Cocinar a fuego medio-bajo tapado durante 20 minutos hasta que las papas y el zapallo estén suaves.',
      'Servir bien caliente con cilantro fresco encima.',
    ],
  },
  {
    id: 'alm-03',
    nombre: 'Pollo al Jugo con Arroz Graneado y Zanahorias Glaseadas',
    descripcion: 'Trutro corto o pechuga de pollo cocida al jugo en su caldo con orégano y pimentón, servida con arroz blanco graneado.',
    categoria: 'almuerzo',
    tiempoMinutos: 30,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 690,
      proteinas: 56,
      carbohidratos: 78,
      grasas: 16,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada o filetes', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Arroz blanco grado 1', cantidad: 80, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz grado 1' },
      { nombre: 'Cebolla y pimentón rojo en juliana', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'pimenton rojo' },
      { nombre: 'Zanahoria en rodajas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zanahoria' },
      { nombre: 'Aceite vegetal o de oliva', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano y ajo en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Sellar el pollo con sal, ajo y orégano en olla amplia con la mitad del aceite hasta dorar.',
      'Añadir la cebolla, el pimentón y la zanahoria. Sofreír 5 minutos.',
      'Agregar media taza de agua caliente, tapar y cocinar a fuego bajo 15 minutos formando un jugo espeso.',
      'Aparte, granear el arroz en una olla pequeña con un toque de aceite y sal con agua hirviendo durante 20 minutos con tostador.',
      'Servir el pollo bañado con abundante jugo sobre el arroz.',
    ],
  },
  {
    id: 'alm-04',
    nombre: 'Cazuela de Ave Casera con Choclo, Zapallo y Papas',
    descripcion: 'El caldo reparador del sur de Chile: pechuga o trutro entero desgrasado, trozo de choclo, zapallo dulce y caldo aromatizado con apio.',
    categoria: 'almuerzo',
    tiempoMinutos: 40,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 4,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 590,
      proteinas: 54,
      carbohidratos: 58,
      grasas: 15,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo entera sin piel', cantidad: 250, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo entera' },
      { nombre: 'Papa grande entera pelada', cantidad: 150, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Trozo de zapallo camote', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo camote' },
      { nombre: 'Trozo de choclo entero con coronta', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'choclo entero' },
      { nombre: 'Apio y pimentón', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'apio' },
      { nombre: 'Arroz blanco', cantidad: 20, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Cilantro fresco', cantidad: 5, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true },
    ],
    instrucciones: [
      'En olla alta hervir 600 ml de agua con apio, pimentón y sal gruesa.',
      'Incorporar la pechuga de pollo y cocinar 10 minutos retirando la espuma superficial.',
      'Agregar la papa entera, el trozo de zapallo, el choclo y el puñadito de arroz.',
      'Bajar a fuego suave y cocinar tapado durante 25 minutos.',
      'Servir en plato hondo de greda con el caldo transparente, espolvoreando cilantro picado fino.',
    ],
  },
  {
    id: 'alm-05',
    nombre: 'Lomo de Cerdo al Horno con Camote Rústico y Ensalada de Espinacas',
    descripcion: 'Medallón grueso de lomo centro de cerdo magro horneado con romero y mostaza, con rodajas de camote dorado.',
    categoria: 'almuerzo',
    tiempoMinutos: 30,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno', // categoria carne magra
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 640,
      proteinas: 55,
      carbohidratos: 62,
      grasas: 17,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Lomo centro de cerdo magro desgrasado', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'lomo centro cerdo' },
      { nombre: 'Camote naranja en rodajas', cantidad: 220, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'camote' },
      { nombre: 'Espinacas baby lavadas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'espinaca' },
      { nombre: 'Aceite de oliva', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Mostaza y orégano', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'mostaza' },
    ],
    instrucciones: [
      'Precalentar el horno a 200°C.',
      'Pintar el lomo de cerdo con mostaza, ajo, sal y romero seco.',
      'Disponer en bandeja el lomo junto al camote cortado en rodajas y rociado con aceite de oliva.',
      'Hornear durante 25 minutos hasta que el cerdo esté a punto y el camote caramelizado.',
      'Servir acompañado de una cama de espinacas frescas.',
    ],
  },
  {
    id: 'alm-06',
    nombre: 'Salmón Sureño a la Plancha con Puré de Zapallo Camote y Champiñones',
    descripcion: 'Filete de salmón fresco de la zona sur sellado a fuego vivo con puré sedoso de zapallo camote y champiñones salteados.',
    categoria: 'almuerzo',
    tiempoMinutos: 20,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 660,
      proteinas: 48,
      carbohidratos: 42,
      grasas: 28,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Filete de salmón fresco o congelado', cantidad: 200, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'salmon porciones' },
      { nombre: 'Zapallo camote', cantidad: 300, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo camote' },
      { nombre: 'Champiñones laminados', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champinones' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Nuez moscada y sal marina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Cocer el zapallo camote al vapor o en agua durante 15 minutos. Moler con pizca de nuez moscada y sal hasta formar un puré suave.',
      'Saltear los champiñones en sartén con gotas de aceite y sal durante 4 minutos.',
      'En plancha o sartén de hierro bien caliente, sellar el salmón por el lado de la piel 4 minutos, voltear y cocinar 3 minutos más.',
      'Montar el filete sobre el puré dorado con los champiñones por encima.',
    ],
  },
  {
    id: 'alm-07',
    nombre: 'Pastel de Papas Magro con Posta y Huevo Duro',
    descripcion: 'Pino sabroso de posta de vacuno magra picada con cebolla y huevo duro, cubierto de puré de papas gratinado.',
    categoria: 'almuerzo',
    tiempoMinutos: 40,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 4,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 710,
      proteinas: 58,
      carbohidratos: 68,
      grasas: 21,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Posta negra molida magra (tártaro o 4% grasa)', cantidad: 220, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'carne molida magra' },
      { nombre: 'Papas peladas para puré', cantidad: 240, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Cebolla picada fina', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Huevo duro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Aceitunas negras sin carozo', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'aceitunas negras' },
      { nombre: 'Comino, ají de color y orégano', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Preparar el pino sofriendo la cebolla en sartén, agregar la carne molida magra, comino, ají de color y sal hasta cocinar.',
      'Cocer las papas y hacer un puré firme con toque de leche descremada y sal.',
      'En fuente para horno, colocar la base de pino, rodajas de huevo duro y aceitunas.',
      'Cubrir con el puré de papas emparejando con tenedor para formar rayas decorativas.',
      'Gratinar al horno a 220°C por 12 minutos hasta que la superficie esté dorada y crocante.',
    ],
  },
  {
    id: 'alm-08',
    nombre: 'Arroz Chaufa Fit de Pollo y Huevo con Pimentón y Cebollín',
    descripcion: 'Arroz salteado al wok a alta temperatura con pechuga de pollo en tiras, huevo revuelto, cebollín y toque de salsa inglesa o condimento suave.',
    categoria: 'almuerzo',
    tiempoMinutos: 20,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 680,
      proteinas: 55,
      carbohidratos: 74,
      grasas: 16,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo cortada en cubos', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Arroz cocido del día anterior', cantidad: 200, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz' },
      { nombre: 'Huevos de gallina batidos', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Cebollín fresco en rodajas', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebollin' },
      { nombre: 'Pimentón rojo en tiritas', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'pimenton' },
      { nombre: 'Aceite de sésamo u oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Salsa inglesa o condimento', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar el wok a fuego máximo con unas gotas de aceite.',
      'Cocinar el huevo batido rápidamente rompiéndolo en migas y retirar.',
      'Dorar el pollo sazonado con ajo y jengibre hasta sellar por completo.',
      'Añadir el pimentón, el cebollín y el arroz cocido bien frío desgranándolo.',
      'Saltear a fuego fuerte 3 minutos, reincorporar el huevo y sazonar.',
    ],
  },
  {
    id: 'alm-09',
    nombre: 'Bistec de Posta Negra con Arroz Integral y Ensalada de Betarraga',
    descripcion: 'Corte magro de posta negra tierna a la plancha con arroz integral graneado y betarragas cocidas en cubos.',
    categoria: 'almuerzo',
    tiempoMinutos: 25,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 630,
      proteinas: 54,
      carbohidratos: 66,
      grasas: 15,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Bistec de posta negra o asiento', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra bistec' },
      { nombre: 'Arroz integral', cantidad: 75, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'arroz integral' },
      { nombre: 'Betarraga cocida en cubos', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'betarraga' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Ajo y perejil picado', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'frutas_verduras', opcional: true },
    ],
    instrucciones: [
      'Cocer el arroz integral a fuego suave por 30 minutos con el doble de agua.',
      'Sazonar el bistec con sal marina, ajo machacado y pimienta.',
      'Sellar en sartén bien caliente durante 2 a 3 minutos por lado para conservar sus jugos.',
      'Aliñar las betarragas con gotas de limón y aceite de oliva.',
      'Servir caliente.',
    ],
  },
  {
    id: 'alm-10',
    nombre: 'Pavo al Horno con Quinoa del Sur y Verduras Salteadas',
    descripcion: 'Pechuga de pavo asada a las finas hierbas con quinoa real lavada y salteado de zapallitos italianos y zanahorias.',
    categoria: 'almuerzo',
    tiempoMinutos: 30,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 610,
      proteinas: 58,
      carbohidratos: 58,
      grasas: 14,
      fibra: 9,
    },
    ingredientes: [
      { nombre: 'Pechuga de pavo fileteada', cantidad: 250, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga de pavo' },
      { nombre: 'Quinoa blanca lavada', cantidad: 70, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'quinoa' },
      { nombre: 'Zapallito italiano en medias lunas', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallito italiano' },
      { nombre: 'Zanahoria en juliana', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zanahoria' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Cocer la quinoa en olla con 2 partes de agua por 1 de quinoa durante 15 minutos hasta que esté transparente.',
      'Saltear en sartén los zapallitos y la zanahoria con aceite de oliva y sal.',
      'Dorar el pavo a la plancha con romero y orégano por 4 minutos cada lado.',
      'Mezclar las verduras con la quinoa tibia y colocar el pavo asado encima.',
    ],
  },
  {
    id: 'alm-11',
    nombre: 'Merluza Austral al Vapor con Papas al Romero y Ensalada Verde',
    descripcion: 'Corte tierno de merluza austral al vapor con gotas de limón, papas rústicas al romero y lechuga costina.',
    categoria: 'almuerzo',
    tiempoMinutos: 20,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 46,
      carbohidratos: 56,
      grasas: 12,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Filete de merluza austral fresca o congelada', cantidad: 250, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'merluza filete' },
      { nombre: 'Papas medianas con piel', cantidad: 220, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Lechuga costina lavada', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'lechuga costina' },
      { nombre: 'Aceite de oliva', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Limón y romero seco', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Cortar las papas en gajos y hervir 10 minutos. Luego saltear en sartén con aceite y romero hasta dorar.',
      'Cocinar la merluza al vapor o a la plancha a fuego medio 3 minutos por lado con jugo de limón y sal.',
      'Acompañar con lechuga costina aliñada con limón y aceite de oliva.',
    ],
  },
  {
    id: 'alm-12',
    nombre: 'Pasta Proteica con Carne Mechada de Vacuno Magro y Salsa de Tomate Natural',
    descripcion: 'Fideos spaghetti al dente bañados en deshilachado de carne mechada magra cocida a fuego lento con salsa de tomates naturales y albahaca.',
    categoria: 'almuerzo',
    tiempoMinutos: 35,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 4,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 730,
      proteinas: 60,
      carbohidratos: 82,
      grasas: 16,
      fibra: 7,
    },
    ingredientes: [
      { nombre: 'Posta negra o choclillo en carne mechada deshilachada', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'choclillo posta' },
      { nombre: 'Fideos spaghetti o tallarines', cantidad: 85, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'tallarines spaghetti' },
      { nombre: 'Salsa de tomate natural o passata sin azúcar', cantidad: 150, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'salsa de tomate' },
      { nombre: 'Cebolla y zanahoria rallada', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Albahaca u orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Cocer la carne a fuego lento con cebolla, zanahoria y orégano hasta que esté tierna y deshilachable.',
      'Añadir la salsa de tomate natural y reducir 10 minutos.',
      'Hervir los tallarines en abundante agua con sal durante 8 a 9 minutos hasta que estén al dente.',
      'Mezclar los fideos calientes con la mechada en su salsa y servir con albahaca fresca.',
    ],
  },

  // ==========================================
  // COLACIONES (6)
  // ==========================================
  {
    id: 'col-01',
    nombre: 'Yogurt Proteico con Frutos Rojos y Nueces',
    descripcion: 'Tote de yogurt tipo griego alto en proteína (15g+ proteína) con frutillas frescas de temporada y nueces picadas.',
    categoria: 'colacion',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 290,
      proteinas: 22,
      carbohidratos: 24,
      grasas: 11,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Yogurt Protein natural o saborizado sin azúcar', cantidad: 200, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt protein' },
      { nombre: 'Frutillas o frambuesas frescas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'frutillas' },
      { nombre: 'Nueces partidas', cantidad: 15, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'nueces' },
    ],
    instrucciones: [
      'Verter el yogurt en un tazón.',
      'Lavar las frutillas y cortarlas en cuartos.',
      'Agregar las frutas y las nueces picadas sobre el yogurt.',
    ],
  },
  {
    id: 'col-02',
    nombre: 'Huevos Duros Sureños con Sal Marina y Bastones de Zanahoria',
    descripcion: 'Dos huevos duros cocidos a punto firme con bastones crujientes de zanahoria fresca.',
    categoria: 'colacion',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 6,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 210,
      proteinas: 15,
      carbohidratos: 10,
      grasas: 11,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Zanahoria fresca pelada', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zanahoria' },
      { nombre: 'Sal marina y orégano', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Hervir los huevos en agua durante 9 minutos. Enfriar bajo el chorro de agua fría y pelar.',
      'Cortar la zanahoria en bastones delgados.',
      'Servir con una pizca de sal marina.',
    ],
  },
  {
    id: 'col-03',
    nombre: 'Shake de Proteína con Leche y Plátano',
    descripcion: 'Batido pre/post entreno rápido con leche con proteína, plátano maduro y un toque de canela.',
    categoria: 'colacion',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 320,
      proteinas: 26,
      carbohidratos: 48,
      grasas: 3,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína (Protein+)', cantidad: 300, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Plátano maduro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'platano' },
      { nombre: 'Canela en polvo', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner la leche con proteína y el plátano pelado en la juguera o licuadora personal.',
      'Licuar a máxima potencia por 30 segundos hasta que esté espumoso.',
      'Espolvorear canela y beber frío de inmediato.',
    ],
  },
  {
    id: 'col-04',
    nombre: 'Rollitos de Pechuga de Pavo con Quesillo y Palta',
    descripcion: 'Láminas de jamón de pavo artesanal enrolladas con barritas de quesillo fresco y tiras de palta.',
    categoria: 'colacion',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'pavo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 260,
      proteinas: 25,
      carbohidratos: 4,
      grasas: 15,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Jamón de pechuga de pavo acaramelado o cocido', cantidad: 100, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon de pavo' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 60, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Palta Hass en bastoncitos', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
    ],
    instrucciones: [
      'Extender las rebanadas de pavo en una tabla limpia.',
      'Colocar un bastón de quesillo y un trozo de palta en cada una.',
      'Enrollar firmemente y asegurar con palillos si es necesario.',
    ],
  },
  {
    id: 'col-05',
    nombre: 'Manzana Verde Crujiente con Ricotta y Miel',
    descripcion: 'Rodajas de manzana verde ácida untadas con queso ricotta suave y un hilo de miel pura.',
    categoria: 'colacion',
    tiempoMinutos: 4,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 240,
      proteinas: 14,
      carbohidratos: 36,
      grasas: 4,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Manzana verde granny smith', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'manzana verde' },
      { nombre: 'Queso ricotta magro', cantidad: 90, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'ricotta' },
      { nombre: 'Miel de abeja pura', cantidad: 8, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'miel' },
    ],
    instrucciones: [
      'Lavar la manzana verde y cortarla en gajos finos.',
      'Disponer la ricotta en un pocillo con el hilo de miel.',
      'Untar cada rebanada crujiente en la ricotta dulce.',
    ],
  },
  {
    id: 'col-06',
    nombre: 'Lata de Atún al Agua con Galletas de Salvado y Limón',
    descripcion: 'Proteína pura al instante: lomo de atún al agua desmenuzado con jugo de limón y galletas crocantes de salvado.',
    categoria: 'colacion',
    tiempoMinutos: 3,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 250,
      proteinas: 32,
      carbohidratos: 22,
      grasas: 3,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Lomitos de atún al agua en conserva', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua lomo' },
      { nombre: 'Galletas de agua integrales o de salvado', cantidad: 5, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'galletas de agua' },
      { nombre: 'Limón y pimienta', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Escurrir el líquido de la lata de atún al agua.',
      'Sazonar en el mismo envase con jugo de limón fresco y pimienta recién molida.',
      'Montar porciones sobre las galletas integrales crujientes.',
    ],
  },

  // ==========================================
  // ONCE CHILENA (8)
  // ==========================================
  {
    id: 'onc-01',
    nombre: 'Once Chilena: Marraqueta con Palta, Huevo Poché y Té Negro',
    descripcion: 'El rito de la once: media marraqueta crujiente con palta recién molida con tenedor, huevo poché y taza de té caliente.',
    categoria: 'once',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 460,
      proteinas: 22,
      carbohidratos: 46,
      grasas: 20,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Huevos de gallina', cantidad: 2, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Palta Hass molida', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Bolsita de té negro ceilán', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'bebidas', opcional: false, terminoBusquedaLider: 'te negro' },
      { nombre: 'Sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Poner la pava o hervidor para el té.',
      'Moler la palta con tenedor agregando una pizca de sal.',
      'Pocher o pasar por agua los dos huevos durante 3 a 4 minutos.',
      'Tostar la marraqueta bien dorada, untar con palta y montar los huevos encima.',
      'Servir junto a la taza de té recién infusionada.',
    ],
  },
  {
    id: 'onc-02',
    nombre: 'Barros Luco Fit en Marraqueta con Posta Magra y Queso Fundido',
    descripcion: 'Homenaje al clásico sánguche chileno preparado con finas láminas de posta negra selladas y queso gouda/chanco derretido con mesura.',
    categoria: 'once',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 560,
      proteinas: 50,
      carbohidratos: 48,
      grasas: 18,
      fibra: 3,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Posta negra en láminas delgadas (bistec)', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Queso chanco o gouda laminado', cantidad: 40, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'queso chanco laminado' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal marina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar una plancha a fuego alto con un toque de aceite.',
      'Sellar las láminas de posta sazonadas con sal durante 1 minuto por lado.',
      'Disponer las láminas de queso sobre la carne en la plancha y tapar unos segundos para fundir.',
      'Tostar la marraqueta e introducir la carne con el queso fundido derramándose.',
      'Servir de inmediato.',
    ],
  },
  {
    id: 'onc-03',
    nombre: 'Ave Palta Proteica en Hallulla Integral',
    descripcion: 'Pechuga de pollo cocida desmenuzada fina mezclada con palta molida y un toque de yogurt natural en vez de mayonesa pesada.',
    categoria: 'once',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 520,
      proteinas: 48,
      carbohidratos: 44,
      grasas: 16,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo cocida y desmenuzada', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Palta Hass molida', cantidad: 50, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'palta hass' },
      { nombre: 'Yogurt natural descremato sin azúcar', cantidad: 30, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'yogurt natural' },
      { nombre: 'Hallulla integral', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'hallulla integral' },
      { nombre: 'Sal y pimienta', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'En un bol mezclar la pechuga de pollo desmenuzada con la palta y el yogurt natural para ligar con cremosidad.',
      'Sazonar con pizca de sal y pimienta recién molida.',
      'Tostar la hallulla integral y rellenar con abundante pasta ave palta.',
    ],
  },
  {
    id: 'onc-04',
    nombre: 'Tostadas de Centeno con Quesillo, Tomate y Orégano del Huerto',
    descripcion: 'Rebanadas de pan de centeno oscuro con generosas lonjas de quesillo sureño de Osorno, tomate maduro y orégano seco.',
    categoria: 'once',
    tiempoMinutos: 5,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: false,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 380,
      proteinas: 28,
      carbohidratos: 42,
      grasas: 10,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pan de centeno o integral denso', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan centeno' },
      { nombre: 'Quesillo de vaca sureño', cantidad: 140, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Tomate chileno en rodajas', cantidad: 100, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Aceite de oliva virgen', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Orégano seco molido', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Tostar el pan de centeno hasta que esté firme y crujiente.',
      'Disponer las láminas de quesillo cubriendo la superficie.',
      'Añadir las rodajas de tomate, un hilo fino de aceite de oliva y abundante orégano.',
    ],
  },
  {
    id: 'onc-05',
    nombre: 'Sánguche de Atún Desmenuzado con Huevo y Lechuga en Marraqueta',
    descripcion: 'Atún al agua mezclado con huevo duro picado y hojas frescas de lechuga dentro de una marraqueta crocante.',
    categoria: 'once',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 44,
      carbohidratos: 48,
      grasas: 12,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Lomo de atún al agua en conserva', cantidad: 120, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'atun al agua' },
      { nombre: 'Huevo duro', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Lechuga escarola o costina', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'lechuga' },
      { nombre: 'Mostaza o toque de yogurt', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Escurrir el atún y mezclar con el huevo duro picado y una cucharadita de mostaza.',
      'Tostar la marraqueta.',
      'Armar el sánguche con las hojas de lechuga y el relleno de atún y huevo.',
    ],
  },
  {
    id: 'onc-06',
    nombre: 'Tazón de Avena con Leche Proteica, Cacao Amargo y Tostada con Mermelada Light',
    descripcion: 'Once reconfortante: tazón de leche caliente batida con avena y cacao amargo chileno, más tostada integral con mermelada sin azúcar.',
    categoria: 'once',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'lacteo',
    aptaPreEntreno: true,
    aptaPostEntreno: false,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 440,
      proteinas: 30,
      carbohidratos: 68,
      grasas: 6,
      fibra: 8,
    },
    ingredientes: [
      { nombre: 'Leche descremada con proteína', cantidad: 250, unidad: 'ml', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'leche protein' },
      { nombre: 'Avena instantánea tradicional', cantidad: 50, unidad: 'g', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'avena instantanea' },
      { nombre: 'Cacao amargo en polvo puro', cantidad: 10, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'cacao amargo en polvo' },
      { nombre: 'Pan de molde integral', cantidad: 1, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Mermelada sin azúcar añadida', cantidad: 20, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'mermelada sin azucar' },
    ],
    instrucciones: [
      'Calentar la leche en una ollita con la avena y el cacao amargo, revolviendo con batidor de mano hasta que tome espesor.',
      'Servir en un tazón grande humeante.',
      'Acompañar con la rebanada tostada untada de mermelada sin azúcar.',
    ],
  },
  {
    id: 'onc-07',
    nombre: 'Paila de Huevos con Jamón de Pavo y Té de Hierbas del Sur',
    descripcion: 'Paila con 3 huevos pochados suavemente sobre jamón de pechuga de pavo doradito, con infusión de poleo o menta fresca.',
    categoria: 'once',
    tiempoMinutos: 8,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 360,
      proteinas: 38,
      carbohidratos: 6,
      grasas: 20,
      fibra: 1,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 3, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Jamón de pechuga de pavo acaramelado', cantidad: 70, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Infusión de hierbas (menta o poleo)', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'bebidas', opcional: false, terminoBusquedaLider: 'infusion hierbas' },
    ],
    instrucciones: [
      'Dorar el jamón de pavo en la paila o sartén pequeña con aceite de oliva durante 1 minuto.',
      'Cascar los huevos encima, bajar el fuego y tapar durante 3 minutos hasta que la clara cuaje y la yema quede líquida.',
      'Servir directamente en la paila caliente junto a la infusión.',
    ],
  },
  {
    id: 'onc-08',
    nombre: 'Sandwich Chacareo Fit en Marraqueta (con Vacuno Magro y Ají Verde)',
    descripcion: 'Versión adaptada: tiernas láminas de posta negra, tomate maduro y rodajas de ají verde fresco en marraqueta crujiente.',
    categoria: 'once',
    tiempoMinutos: 10,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 510,
      proteinas: 46,
      carbohidratos: 48,
      grasas: 13,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Marraqueta fresca', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'marraqueta' },
      { nombre: 'Posta negra en láminas delgadas', cantidad: 180, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra' },
      { nombre: 'Tomate chileno en rodajas', cantidad: 80, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'tomate' },
      { nombre: 'Ají verde chileno en tiritas finas', cantidad: 20, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'aji verde' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
    ],
    instrucciones: [
      'Sellar la posta negra en plancha caliente con sal y pimienta 2 minutos.',
      'Tostar la marraqueta.',
      'Colocar la carne jugosa, cubrir con rodajas de tomate fresco y coronar con tiritas de ají verde.',
      'Cerrar el sándwich y apretar con suavidad para que el jugo empape la miga.',
    ],
  },

  // ==========================================
  // CENAS (6)
  // ==========================================
  {
    id: 'cen-01',
    nombre: 'Filete de Merluza al Horno con Papas Cocidas y Espinacas al Vapor',
    descripcion: 'Cena digestiva y alta en proteína: filete blanco de merluza con papas cocidas al vapor, espinacas y toque de aceite de oliva.',
    categoria: 'cena',
    tiempoMinutos: 20,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 480,
      proteinas: 48,
      carbohidratos: 44,
      grasas: 11,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Filete de merluza austral fresca o congelada', cantidad: 250, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'merluza filete' },
      { nombre: 'Papas pequeñas hervidas', cantidad: 200, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Espinacas lavadas', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'espinaca' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Limón y sal de mar', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Disponer la merluza en una fuente para horno con gotas de limón, sal y pimienta.',
      'Hornear a 190°C durante 12 a 15 minutos.',
      'Cocer las papas en agua y vaporizar las espinacas en sartén durante 3 minutos.',
      'Servir caliente rociado con aceite de oliva.',
    ],
  },
  {
    id: 'cen-02',
    nombre: 'Pechuga de Pollo Salteada al Wok con Zapallitos Italianos y Champiñones',
    descripcion: 'Pechuga en tiritas salteada rápidamente con zapallitos en medias lunas, champiñones frescos y semillas de sésamo.',
    categoria: 'cena',
    tiempoMinutos: 15,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 460,
      proteinas: 54,
      carbohidratos: 16,
      grasas: 18,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo deshuesada en tiritas', cantidad: 240, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Zapallito italiano', cantidad: 180, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallito italiano' },
      { nombre: 'Champiñones laminados', cantidad: 120, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'champinones' },
      { nombre: 'Aceite de oliva virgen', cantidad: 10, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Ajo picado y orégano', cantidad: 1, unidad: 'cucharadita', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Calentar la sartén o wok con aceite de oliva a fuego alto.',
      'Dorar las tiritas de pollo sazonadas con sal y ajo por 4 minutos.',
      'Incorporar los zapallitos y los champiñones.',
      'Saltear moviendo constantemente por 5 minutos manteniendo las verduras crujientes.',
      'Servir caliente.',
    ],
  },
  {
    id: 'cen-03',
    nombre: 'Tartar Clásico de Posta Negra (Crudo Sureño) con Tostadas Integrales',
    descripcion: 'Inspirado en el crudo valdiviano/sureño: posta negra extra magra picada finísima a cuchillo con limón, cebolla amortiguada, alcaparras y tostadas.',
    categoria: 'cena',
    tiempoMinutos: 12,
    porciones: 1,
    fuenteProteinaPrincipal: 'vacuno',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 490,
      proteinas: 52,
      carbohidratos: 36,
      grasas: 13,
      fibra: 4,
    },
    ingredientes: [
      { nombre: 'Posta negra molida tártaro fresca o picada a cuchillo', cantidad: 230, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'posta negra tartaro' },
      { nombre: 'Cebolla picada fina en brunoise', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Jugo de limón fresco exprimido', cantidad: 25, unidad: 'ml', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'limon' },
      { nombre: 'Pan de molde integral tostado', cantidad: 2, unidad: 'rebanada', categoriaPasillo: 'panaderia_cereales', opcional: false, terminoBusquedaLider: 'pan molde integral' },
      { nombre: 'Pepinillos o alcaparras picadas', cantidad: 20, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: true, terminoBusquedaLider: 'pepinillos' },
      { nombre: 'Aceite de oliva y ají verde', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Mantener la carne muy fría en el refrigerador hasta el momento de preparar.',
      'Mezclar en un bol la posta picada, la cebolla, pepinillos picados, sal y pimienta.',
      'Rociar con el jugo de limón y gotas de aceite de oliva justo antes de servir para no sobrecocinar la carne.',
      'Acompañar con las rebanadas de pan integral tostadas crocantes.',
    ],
  },
  {
    id: 'cen-04',
    nombre: 'Tortilla Española Fit de Papas y Claras con Jamón de Pavo',
    descripcion: 'Papas hervidas cortadas en láminas cuajadas en sartén con 4 claras, 1 huevo entero y cubos de jamón de pechuga de pavo.',
    categoria: 'cena',
    tiempoMinutos: 15,
    porciones: 1,
    fuenteProteinaPrincipal: 'huevos',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 470,
      proteinas: 42,
      carbohidratos: 46,
      grasas: 12,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Huevos de gallina', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'huevos' },
      { nombre: 'Claras de huevo', cantidad: 4, unidad: 'unidad', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'claras de huevo' },
      { nombre: 'Papas cocidas en rodajas finas', cantidad: 200, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'papas' },
      { nombre: 'Jamón de pavo en cubitos', cantidad: 60, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'jamon pavo' },
      { nombre: 'Aceite de oliva', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Sal fina', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Batir el huevo y las claras con sal en un bol amplio.',
      'Agregar las papas cocidas y los cubitos de jamón de pavo.',
      'Calentar la sartén antiadherente con aceite de oliva a fuego medio-bajo.',
      'Verter la mezcla y cocinar 4 minutos por lado dando vuelta con ayuda de un plato.',
      'Servir dorada y esponjosa.',
    ],
  },
  {
    id: 'cen-05',
    nombre: 'Sopa Crema de Zapallo Camote con Pollo Desmenuzado y Semillas',
    descripcion: 'Crema aterciopelada y tibia de zapallo camote con caldo casero, coronada con pechuga de pollo desmenuzada y semillas de zapallo.',
    categoria: 'cena',
    tiempoMinutos: 25,
    porciones: 1,
    fuenteProteinaPrincipal: 'pollo',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: true,
    batchCookingRinde: 3,
    esFavorita: false,
    macrosPorPorcion: {
      calorias: 440,
      proteinas: 50,
      carbohidratos: 36,
      grasas: 10,
      fibra: 6,
    },
    ingredientes: [
      { nombre: 'Pechuga de pollo cocida y desmenuzada', cantidad: 200, unidad: 'g', categoriaPasillo: 'carnes_aves', opcional: false, terminoBusquedaLider: 'pechuga pollo' },
      { nombre: 'Zapallo camote cocido', cantidad: 280, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'zapallo camote' },
      { nombre: 'Cebolla sofrita', cantidad: 40, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'cebolla' },
      { nombre: 'Semillas de zapallo o maravilla', cantidad: 10, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'semillas de zapallo' },
      { nombre: 'Aceite de oliva', cantidad: 5, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Jengibre rallado y sal', cantidad: 1, unidad: 'pizca', categoriaPasillo: 'despensa_abarrotes', opcional: true },
    ],
    instrucciones: [
      'Licuar el zapallo camote cocido con la cebolla sofrita y un poco de caldo caliente hasta obtener una crema suave.',
      'Calentar la crema en una olla añadiendo jengibre fresco rallado y sal.',
      'Servir en plato hondo bien caliente.',
      'Colocar encima la pechuga de pollo desmenuzada y terminar con las semillas tostadas.',
    ],
  },
  {
    id: 'cen-06',
    nombre: 'Ensalada Tibia de Salmón con Quinoa, Rúcula y Quesillo',
    descripcion: 'Cubos de salmón dorado a la plancha servidos tibios sobre una base fresca de quinoa, hojas de rúcula y dados de quesillo.',
    categoria: 'cena',
    tiempoMinutos: 15,
    porciones: 1,
    fuenteProteinaPrincipal: 'pescado',
    aptaPreEntreno: false,
    aptaPostEntreno: true,
    batchCooking: false,
    esFavorita: true,
    macrosPorPorcion: {
      calorias: 530,
      proteinas: 46,
      carbohidratos: 34,
      grasas: 22,
      fibra: 5,
    },
    ingredientes: [
      { nombre: 'Salmón fresco o congelado en cubos', cantidad: 180, unidad: 'g', categoriaPasillo: 'pescados_mariscos', opcional: false, terminoBusquedaLider: 'salmon porciones' },
      { nombre: 'Quinoa cocida', cantidad: 120, unidad: 'g', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'quinoa' },
      { nombre: 'Quesillo sureño en dados', cantidad: 60, unidad: 'g', categoriaPasillo: 'lacteos_huevos', opcional: false, terminoBusquedaLider: 'quesillo' },
      { nombre: 'Rúcula fresca o espinaca baby', cantidad: 60, unidad: 'g', categoriaPasillo: 'frutas_verduras', opcional: false, terminoBusquedaLider: 'rucula' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 8, unidad: 'ml', categoriaPasillo: 'despensa_abarrotes', opcional: false, terminoBusquedaLider: 'aceite de oliva' },
      { nombre: 'Limón y sal', cantidad: 1, unidad: 'unidad', categoriaPasillo: 'frutas_verduras', opcional: true, terminoBusquedaLider: 'limon' },
    ],
    instrucciones: [
      'Dorar los cubos de salmón en sartén con gotas de aceite por 3 minutos hasta que tomen color dorado.',
      'En un bol mezclar la rúcula, la quinoa cocida tibia y los dados de quesillo.',
      'Incorporar el salmón caliente.',
      'Aliñar con limón y aceite de oliva virgen extra.',
    ],
  },
];
